/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;
import controlador.ControladorAgenda; 
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import modelo.Agenda;
import modelo.Usuario;
import javax.swing.table.DefaultTableModel;
import java.util.Iterator;
/**
 *
 * @author LENOVO
 */
public class FRMAgenda extends javax.swing.JInternalFrame {
    ControladorAgenda agendaController = new ControladorAgenda();
    private Usuario usuarioActual;

    public FRMAgenda() {
        this(null);
    }

    public FRMAgenda(Usuario usuario) {
        initComponents();
        this.usuarioActual = usuario;
        TXTIdAgenda.setValue(0);
        TXTIdAgenda.setVisible(false);
        limpiarFormulario();
    }
    private void limpiarFormulario() {
    TXTIdAgenda.setValue(0);
    TXTDiasemana.setText("Escribe dia de la semana");
    TXTHorainicio.setText("Escribe hora de inicio");
    TXTHorafin.setText("Escribe hora de fin");
    TXTBuscarAgenda.setText("Escribe texto a buscar");
    btnModificar.setEnabled(false);
    btnEliminar.setEnabled(false);
    llenarTabla();
}
    public void llenarTabla(){
    Agenda unAgenda = new Agenda();
    DefaultTableModel tabla = (DefaultTableModel)tblAgenda.getModel();
    Iterator<Agenda> itAgenda = unAgenda.listar();
    Object[] filaAgenda = new Object[tblAgenda.getColumnCount()];
    tabla.setRowCount(0); 
    while (itAgenda.hasNext()) { 
        unAgenda = itAgenda.next();
        filaAgenda[0] = unAgenda.getIdagenda();
        filaAgenda[1] = unAgenda.getDiasemana();
        filaAgenda[2] = unAgenda.getHorainicio();       
        filaAgenda[3] = unAgenda.getHorafin();
        tabla.addRow(filaAgenda);
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TXTDiasemana = new javax.swing.JTextField();
        TXTIdAgenda = new javax.swing.JFormattedTextField();
        btnLimpiar = new javax.swing.JButton();
        btnInsertar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        TXTHorainicio = new javax.swing.JTextField();
        TXTHorafin = new javax.swing.JTextField();
        TXTBuscarAgenda = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAgenda = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("                                 Formulario de Agenda");

        jPanel1.setBackground(new java.awt.Color(217, 181, 253));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jLabel1.setText("Dia Semana");

        TXTDiasemana.setBackground(new java.awt.Color(226, 204, 248));
        TXTDiasemana.setFont(new java.awt.Font("Sylfaen", 0, 12)); // NOI18N
        TXTDiasemana.setText("Escribe dia de la semana");

        TXTIdAgenda.setBackground(new java.awt.Color(235, 219, 250));
        TXTIdAgenda.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        btnLimpiar.setBackground(new java.awt.Color(204, 204, 255));
        btnLimpiar.setFont(new java.awt.Font("Tw Cen MT", 2, 14)); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 0, 204)));
        btnLimpiar.addActionListener(this::btnLimpiarActionPerformed);

        btnInsertar.setBackground(new java.awt.Color(204, 204, 255));
        btnInsertar.setFont(new java.awt.Font("Tw Cen MT", 2, 14)); // NOI18N
        btnInsertar.setText("Insertar");
        btnInsertar.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 0, 153)));
        btnInsertar.addActionListener(this::btnInsertarActionPerformed);

        btnModificar.setBackground(new java.awt.Color(204, 204, 255));
        btnModificar.setFont(new java.awt.Font("Tw Cen MT", 2, 14)); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 0, 153)));
        btnModificar.addActionListener(this::btnModificarActionPerformed);

        btnCerrar.setBackground(new java.awt.Color(204, 204, 255));
        btnCerrar.setFont(new java.awt.Font("Tw Cen MT", 2, 14)); // NOI18N
        btnCerrar.setText("Cerrar");
        btnCerrar.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 0, 153)));
        btnCerrar.addActionListener(this::btnCerrarActionPerformed);

        btnEliminar.setBackground(new java.awt.Color(204, 204, 255));
        btnEliminar.setFont(new java.awt.Font("Tw Cen MT", 2, 14)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 0, 153)));
        btnEliminar.addActionListener(this::btnEliminarActionPerformed);

        TXTHorainicio.setBackground(new java.awt.Color(236, 217, 255));
        TXTHorainicio.setFont(new java.awt.Font("Sylfaen", 0, 12)); // NOI18N
        TXTHorainicio.setText("Escribe hora de inicio");

        TXTHorafin.setBackground(new java.awt.Color(231, 212, 249));
        TXTHorafin.setFont(new java.awt.Font("Sylfaen", 0, 12)); // NOI18N
        TXTHorafin.setText("Escribe hora de fin");

        TXTBuscarAgenda.setBackground(new java.awt.Color(229, 211, 248));
        TXTBuscarAgenda.setFont(new java.awt.Font("Sylfaen", 0, 12)); // NOI18N
        TXTBuscarAgenda.setText("Escribe texto a buscar");
        TXTBuscarAgenda.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TXTBuscarAgendaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TXTBuscarAgendaFocusLost(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jLabel4.setText("Buscar");

        btnBuscar.setBackground(new java.awt.Color(204, 204, 255));
        btnBuscar.setFont(new java.awt.Font("Tw Cen MT", 2, 14)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 0, 153)));
        btnBuscar.addActionListener(this::btnBuscarActionPerformed);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jLabel3.setText("Hora Fin");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jLabel2.setText("Hora Inicio");

        tblAgenda.setBackground(new java.awt.Color(228, 211, 245));
        tblAgenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Dia semana", "Hora inicio", "Hora fin"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblAgenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAgendaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblAgenda);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TXTDiasemana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TXTBuscarAgenda, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TXTHorainicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TXTHorafin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(TXTIdAgenda, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnInsertar, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(139, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TXTIdAgenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInsertar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(TXTHorainicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(26, 26, 26)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(TXTBuscarAgenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscar)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TXTDiasemana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TXTHorafin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        // TODO add your handling code here:
           doDefaultCloseAction();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarActionPerformed
        // TODO add your handling code here:
         agendaController.controlarAccion(evt, obtenerAgenda());
        limpiarFormulario();
    }//GEN-LAST:event_btnInsertarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        agendaController.controlarAccion(evt, obtenerAgenda());
        limpiarFormulario();
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        agendaController.controlarAccion(evt, obtenerAgenda());
        limpiarFormulario();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void tblAgendaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAgendaMouseClicked
        // TODO add your handling code here:
            if(evt.getClickCount()==2){
            int fila = tblAgenda.rowAtPoint(evt.getPoint());
            if(fila>-1){
                TXTIdAgenda.setValue((Integer)tblAgenda.getValueAt(fila, 0));
                TXTDiasemana.setText((String)tblAgenda.getValueAt(fila, 1));
                TXTHorainicio.setText((String)tblAgenda.getValueAt(fila, 2));
                TXTHorafin.setText((String)tblAgenda.getValueAt(fila, 3));
                btnModificar.setEnabled(true);
                btnEliminar.setEnabled(true);
                
            }
        }
    }//GEN-LAST:event_tblAgendaMouseClicked

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
         llenarTablaConBusqueda(TXTBuscarAgenda.getText());
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void TXTBuscarAgendaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TXTBuscarAgendaFocusGained
        // TODO add your handling code here:
        if (TXTBuscarAgenda.getText().equals("Escribe texto a buscar")){
            TXTBuscarAgenda.setText("");
        } 
    }//GEN-LAST:event_TXTBuscarAgendaFocusGained

    private void TXTBuscarAgendaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TXTBuscarAgendaFocusLost
        // TODO add your handling code here:
        if (TXTBuscarAgenda.getText().isEmpty()){
            TXTBuscarAgenda.setText("Escribe texto a buscar");
        }
    }//GEN-LAST:event_TXTBuscarAgendaFocusLost

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        limpiarFormulario();
    }//GEN-LAST:event_btnLimpiarActionPerformed
    private Agenda obtenerAgenda(){
    Agenda elAgenda = new Agenda();
    DateTimeFormatter timeFormatter = DateTimeFormatter.ofPattern("H:m");
    elAgenda.setIdagenda((Integer) TXTIdAgenda.getValue());
    String dia = TXTDiasemana.getText().trim();
    if (!dia.isEmpty() && !dia.equals("Escribe dia de la semana")) {
        elAgenda.setDiasemana(dia);
    }
    String horaI = TXTHorainicio.getText().trim();
    String horaF = TXTHorafin.getText().trim();
    if (!horaI.isEmpty() && !horaI.equals("Escribe hora de inicio")) {
        elAgenda.setHorainicio(LocalTime.parse(horaI, timeFormatter));
    }
    if (!horaF.isEmpty() && !horaF.equals("Escribe hora de fin")) {
        elAgenda.setHorafin(LocalTime.parse(horaF, timeFormatter));
    }
    if (usuarioActual != null) {
        elAgenda.setIdusuario(usuarioActual.getIdUsuario());
    }
    return elAgenda;
}
    private void llenarTablaConBusqueda(String busqueda){
    Agenda unAgenda = new Agenda();
    DefaultTableModel tabla = (DefaultTableModel)tblAgenda.getModel();
    Iterator<Agenda> itAgenda = unAgenda.buscar(busqueda);
    Object[] filaAgenda = new Object[tblAgenda.getColumnCount()];
    tabla.setRowCount(0); 
    while (itAgenda.hasNext()) {
    unAgenda = itAgenda.next();
    filaAgenda[0] = unAgenda.getIdagenda();
    filaAgenda[1] = unAgenda.getDiasemana();
    filaAgenda[2] = unAgenda.getHorainicio();
    filaAgenda[3] = unAgenda.getHorafin();
    ((DefaultTableModel)tblAgenda.getModel()).addRow(filaAgenda);
}
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TXTBuscarAgenda;
    private javax.swing.JTextField TXTDiasemana;
    private javax.swing.JTextField TXTHorafin;
    private javax.swing.JTextField TXTHorainicio;
    private javax.swing.JFormattedTextField TXTIdAgenda;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnInsertar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblAgenda;
    // End of variables declaration//GEN-END:variables
}
