/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;
import controlador.ControladorBloqueos; 
import modelo.Bloqueos;             
import javax.swing.table.DefaultTableModel;
import java.util.Iterator;
import java.util.Date;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.ZoneId;
/**
 *
 * @author LENOVO
 */
public class FRMBloqueos extends javax.swing.JInternalFrame {
    ControladorBloqueos BloqueosController = new ControladorBloqueos();

    /**
     * Creates new form FRMBloqueos
     */
    public FRMBloqueos() {
        initComponents();
        TXTIdBloqueos.setValue(0);
        TXTIdBloqueos.setVisible(false);
        limpiarFormulario();
    }
    private void limpiarFormulario() {
    TXTIdBloqueos.setValue(0);
    spnFecha.setValue(new java.util.Date());
    spnHora.setValue(new java.util.Date());
    spnFecha_creacion.setValue(new java.util.Date());
    TXTMotivo.setText("Escribe motivo");
    spnCreado_por.setValue(0);
    TXTBuscarBloqueos.setText("Escribe el texto a buscar");
    btnModificar.setEnabled(false);
    btnEliminar.setEnabled(false);
    llenarTabla();
}
    public void llenarTabla(){
    Bloqueos unBloqueos = new Bloqueos();
    DefaultTableModel tabla = (DefaultTableModel)tblBloqueos.getModel();
    Iterator<Bloqueos> itBloqueos = unBloqueos.listar();
    Object[] filaBloqueos = new Object[tblBloqueos.getColumnCount()];
    tabla.setRowCount(0); 
    while (itBloqueos.hasNext()) { 
        unBloqueos = itBloqueos.next();
        filaBloqueos[0] = unBloqueos.getIdbloqueo();
        filaBloqueos[1] = unBloqueos.getFecha();
        filaBloqueos[2] = unBloqueos.getHora_inicio();
        filaBloqueos[3] = unBloqueos.getFecha_creacion();
        filaBloqueos[4] = unBloqueos.getMotivo();
        filaBloqueos[5] = unBloqueos.getCreated_at();
        tabla.addRow(filaBloqueos);
    }
    
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnLimpiar = new javax.swing.JButton();
        btnInsertar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        spnFecha = new javax.swing.JSpinner();
        spnHora = new javax.swing.JSpinner();
        spnFecha_creacion = new javax.swing.JSpinner();
        TXTMotivo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        spnCreado_por = new javax.swing.JSpinner();
        TXTIdBloqueos = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        TXTBuscarBloqueos = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBloqueos = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("                                      Formulario de Bloqueos");

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        btnLimpiar.setBackground(new java.awt.Color(255, 153, 204));
        btnLimpiar.setFont(new java.awt.Font("Tw Cen MT", 2, 14)); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 0, 255)));
        btnLimpiar.addActionListener(this::btnLimpiarActionPerformed);

        btnInsertar.setBackground(new java.awt.Color(255, 153, 204));
        btnInsertar.setFont(new java.awt.Font("Tw Cen MT", 2, 14)); // NOI18N
        btnInsertar.setText("Insertar");
        btnInsertar.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 0, 255)));
        btnInsertar.addActionListener(this::btnInsertarActionPerformed);

        btnModificar.setBackground(new java.awt.Color(255, 153, 204));
        btnModificar.setFont(new java.awt.Font("Tw Cen MT", 2, 14)); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 0, 255)));
        btnModificar.addActionListener(this::btnModificarActionPerformed);

        btnEliminar.setBackground(new java.awt.Color(255, 153, 204));
        btnEliminar.setFont(new java.awt.Font("Tw Cen MT", 2, 14)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 0, 255)));
        btnEliminar.addActionListener(this::btnEliminarActionPerformed);

        btnCerrar.setBackground(new java.awt.Color(255, 153, 204));
        btnCerrar.setFont(new java.awt.Font("Tw Cen MT", 2, 14)); // NOI18N
        btnCerrar.setText("Cerrar");
        btnCerrar.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 0, 255)));
        btnCerrar.addActionListener(this::btnCerrarActionPerformed);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jLabel1.setText("Fecha");

        spnFecha.setModel(new javax.swing.SpinnerDateModel());

        spnHora.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), null, null, java.util.Calendar.HOUR));

        spnFecha_creacion.setModel(new javax.swing.SpinnerDateModel());

        TXTMotivo.setBackground(new java.awt.Color(255, 225, 255));
        TXTMotivo.setText("Escribe motivo");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jLabel2.setText("Hora");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jLabel5.setText("Fecha creacion");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jLabel3.setText("Motivo");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jLabel4.setText("creado por");

        spnCreado_por.setModel(new javax.swing.SpinnerNumberModel());

        TXTIdBloqueos.setBackground(new java.awt.Color(255, 222, 255));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jLabel6.setText("Buscar");

        TXTBuscarBloqueos.setBackground(new java.awt.Color(255, 224, 255));
        TXTBuscarBloqueos.setText("Escribe el texto a buscar");
        TXTBuscarBloqueos.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TXTBuscarBloqueosFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TXTBuscarBloqueosFocusLost(evt);
            }
        });

        btnBuscar.setBackground(new java.awt.Color(255, 153, 204));
        btnBuscar.setFont(new java.awt.Font("Tw Cen MT", 2, 14)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 0, 255)));
        btnBuscar.addActionListener(this::btnBuscarActionPerformed);

        tblBloqueos.setBackground(new java.awt.Color(255, 204, 255));
        tblBloqueos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Fecha", "Hora", "Fecha_creacion", "Motivo", "Creado_por"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblBloqueos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBloqueosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblBloqueos);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TXTMotivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spnFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(TXTIdBloqueos, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(spnCreado_por, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TXTBuscarBloqueos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(spnHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(spnFecha_creacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnInsertar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnModificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnCerrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 514, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(spnFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TXTIdBloqueos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(spnHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2))
                    .addComponent(btnInsertar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(spnFecha_creacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5))
                    .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(TXTMotivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(spnCreado_por, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(TXTBuscarBloqueos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscar)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        limpiarFormulario();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarActionPerformed
        // TODO add your handling code here:
        BloqueosController.controlarAccion(evt, obtenerBloqueos());
        limpiarFormulario();
    }//GEN-LAST:event_btnInsertarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        BloqueosController.controlarAccion(evt, obtenerBloqueos());
        limpiarFormulario();
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        BloqueosController.controlarAccion(evt, obtenerBloqueos());
        limpiarFormulario();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        // TODO add your handling code here:
        doDefaultCloseAction();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void tblBloqueosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBloqueosMouseClicked
        // TODO add your handling code here:
        if(evt.getClickCount()==2){
            int fila = tblBloqueos.rowAtPoint(evt.getPoint());
            if(fila>-1){
                TXTIdBloqueos.setValue((Integer)tblBloqueos.getValueAt(fila, 0));
                LocalDate fecha = (LocalDate) tblBloqueos.getValueAt(fila, 1);
                spnFecha.setValue(Date.from(fecha.atStartOfDay(ZoneId.systemDefault()).toInstant()));
                String horaStr = (String) tblBloqueos.getValueAt(fila, 2);
                spnHora.setValue(java.sql.Time.valueOf(horaStr));
                LocalDateTime fchCreacion = (LocalDateTime) tblBloqueos.getValueAt(fila, 3);
                spnFecha_creacion.setValue(Date.from(fchCreacion.atZone(ZoneId.systemDefault()).toInstant()));
                TXTMotivo.setText((String)tblBloqueos.getValueAt(fila, 4));
                btnModificar.setEnabled(true);
                btnEliminar.setEnabled(true);
            }
        }
    }//GEN-LAST:event_tblBloqueosMouseClicked

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        llenarTablaConBusqueda(TXTBuscarBloqueos.getText());
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void TXTBuscarBloqueosFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TXTBuscarBloqueosFocusGained
        // TODO add your handling code here:
        if (TXTBuscarBloqueos.getText().equals("Escribe el texto a buscar")){
            TXTBuscarBloqueos.setText("");
        }
    }//GEN-LAST:event_TXTBuscarBloqueosFocusGained

    private void TXTBuscarBloqueosFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TXTBuscarBloqueosFocusLost
        // TODO add your handling code here:
        if (TXTBuscarBloqueos.getText().isEmpty()){
            TXTBuscarBloqueos.setText("Escribe el texto a buscar");
        }
    }//GEN-LAST:event_TXTBuscarBloqueosFocusLost

    private Bloqueos obtenerBloqueos(){
    Bloqueos elBloqueos = new Bloqueos();
    elBloqueos.setIdbloqueo((Integer) TXTIdBloqueos.getValue());
    Date fechaDate = (Date) spnFecha.getValue();
    elBloqueos.setFecha(fechaDate.toInstant().atZone(ZoneId.systemDefault()).toLocalDate());
    Date horaDate = (Date) spnHora.getValue();
    elBloqueos.setHora_inicio(String.format("%02d:%02d:%02d",
            horaDate.getHours(), horaDate.getMinutes(), horaDate.getSeconds()));
    Date fechaCreacionDate = (Date) spnFecha_creacion.getValue();
    elBloqueos.setFecha_creacion(fechaCreacionDate.toInstant().atZone(ZoneId.systemDefault()).toLocalDateTime());
    elBloqueos.setMotivo(TXTMotivo.getText());
    return elBloqueos;
}
    private void llenarTablaConBusqueda(String busqueda){
    Bloqueos unBloqueos = new Bloqueos();
    DefaultTableModel tabla = (DefaultTableModel)tblBloqueos.getModel();
    Iterator<Bloqueos> itBloqueos = unBloqueos.buscar(busqueda);
    Object[] filaBloqueos = new Object[tblBloqueos.getColumnCount()];
    tabla.setRowCount(0); 
    while (itBloqueos.hasNext()) {
    unBloqueos = itBloqueos.next();
    filaBloqueos[0] = unBloqueos.getIdbloqueo();
    filaBloqueos[1] = unBloqueos.getFecha();
    filaBloqueos[2] = unBloqueos.getHora_inicio();
    filaBloqueos[3] = unBloqueos.getFecha_creacion();
    filaBloqueos[4] = unBloqueos.getMotivo();
    filaBloqueos[5] = unBloqueos.getCreated_at();
    ((DefaultTableModel)tblBloqueos.getModel()).addRow(filaBloqueos);
}
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TXTBuscarBloqueos;
    private javax.swing.JFormattedTextField TXTIdBloqueos;
    private javax.swing.JTextField TXTMotivo;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnInsertar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner spnCreado_por;
    private javax.swing.JSpinner spnFecha;
    private javax.swing.JSpinner spnFecha_creacion;
    private javax.swing.JSpinner spnHora;
    private javax.swing.JTable tblBloqueos;
    // End of variables declaration//GEN-END:variables
}
