/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;
import controlador.ControladorBloqueos; 
import modelo.Bloqueos;             
import javax.swing.table.DefaultTableModel;
import java.util.Iterator;
import java.util.Date;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.ZoneId;
/**
 *
 * @author LENOVO
 */
public class FRMBloqueos extends javax.swing.JInternalFrame {
    ControladorBloqueos BloqueosController = new ControladorBloqueos();

    /**
     * Creates new form FRMBloqueos
     */
    public FRMBloqueos() {
        initComponents();
        TXTIdBloqueos.setValue(0);
        TXTIdBloqueos.setVisible(false);
        limpiarFormulario();
    }
    private void limpiarFormulario() {
    TXTIdBloqueos.setValue(0);
    spnFecha.setValue(0);
    spnHora.setValue(0);
    spnFecha_creacion.setValue(0);
    TXTMotivo.setText("Escribe motivo");
    spnCreado_por.setValue(0);
    TXTBuscarBloqueos.setText("Escribe el texto a buscar");
    btnModificar.setEnabled(false);
    btnEliminar.setEnabled(false);
    llenarTabla();
}
    public void llenarTabla(){
    Bloqueos unBloqueos = new Bloqueos();
    DefaultTableModel tabla = (DefaultTableModel)tblBloqueos.getModel();
    Iterator<Bloqueos> itBloqueos = unBloqueos.listar();
    Object[] filaBloqueos = new Object[tblBloqueos.getColumnCount()];
    tabla.setRowCount(0); 
    while (itBloqueos.hasNext()) { 
        unBloqueos = itBloqueos.next();
        filaBloqueos[0] = unBloqueos.getIdbloqueo();
        filaBloqueos[1] = unBloqueos.getFecha();
        filaBloqueos[2] = unBloqueos.getHora_inicio();
        filaBloqueos[3] = unBloqueos.getFecha_creacion();
        filaBloqueos[4] = unBloqueos.getMotivo();
        filaBloqueos[5] = unBloqueos.getCreated_at();
        tabla.addRow(filaBloqueos);
    }
    
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLimpiar = new javax.swing.JButton();
        btnInsertar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        spnFecha = new javax.swing.JSpinner();
        spnHora = new javax.swing.JSpinner();
        TXTMotivo = new javax.swing.JTextField();
        TXTBuscarBloqueos = new javax.swing.JTextField();
        spnFecha_creacion = new javax.swing.JSpinner();
        TXTIdBloqueos = new javax.swing.JFormattedTextField();
        spnCreado_por = new javax.swing.JSpinner();
        btnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBloqueos = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("                                      Formulario de Bloqueos");

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(this::btnLimpiarActionPerformed);

        btnInsertar.setText("Insertar");
        btnInsertar.addActionListener(this::btnInsertarActionPerformed);

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(this::btnModificarActionPerformed);

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(this::btnEliminarActionPerformed);

        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(this::btnCerrarActionPerformed);

        jLabel1.setText("Fecha");

        jLabel2.setText("Hora");

        jLabel3.setText("Motivo");

        jLabel4.setText("creado por");

        jLabel5.setText("Fecha creacion");

        jLabel6.setText("Buscar");

        spnFecha.setModel(new javax.swing.SpinnerDateModel());

        spnHora.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), null, null, java.util.Calendar.HOUR));

        TXTMotivo.setText("Escribe motivo");

        TXTBuscarBloqueos.setText("Escribe el texto a buscar");
        TXTBuscarBloqueos.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TXTBuscarBloqueosFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TXTBuscarBloqueosFocusLost(evt);
            }
        });

        spnFecha_creacion.setModel(new javax.swing.SpinnerDateModel());

        spnCreado_por.setModel(new javax.swing.SpinnerNumberModel());

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(this::btnBuscarActionPerformed);

        tblBloqueos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Fecha", "Hora", "Fecha_creacion", "Motivo", "Creado_por"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblBloqueos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBloqueosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblBloqueos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TXTBuscarBloqueos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBuscar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(spnFecha_creacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel2)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(spnHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel1)
                                            .addGap(31, 31, 31)
                                            .addComponent(spnFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(18, 18, 18)
                                .addComponent(TXTIdBloqueos, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TXTMotivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(spnCreado_por, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCerrar)
                            .addComponent(btnEliminar)
                            .addComponent(btnModificar)
                            .addComponent(btnInsertar)
                            .addComponent(btnLimpiar))
                        .addGap(17, 17, 17))))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 506, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimpiar)
                    .addComponent(jLabel1)
                    .addComponent(spnFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TXTIdBloqueos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnInsertar)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(spnHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnModificar)
                    .addComponent(spnFecha_creacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEliminar)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(TXTMotivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnCerrar)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(spnCreado_por, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(TXTBuscarBloqueos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        limpiarFormulario();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarActionPerformed
        // TODO add your handling code here:
        BloqueosController.controlarAccion(evt, obtenerBloqueos());
        limpiarFormulario();
    }//GEN-LAST:event_btnInsertarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        BloqueosController.controlarAccion(evt, obtenerBloqueos());
        limpiarFormulario();
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        BloqueosController.controlarAccion(evt, obtenerBloqueos());
        limpiarFormulario();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        // TODO add your handling code here:
        doDefaultCloseAction();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void tblBloqueosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBloqueosMouseClicked
        // TODO add your handling code here:
        if(evt.getClickCount()==2){
            int fila = tblBloqueos.rowAtPoint(evt.getPoint());
            if(fila>-1){
                TXTIdBloqueos.setValue((Integer)tblBloqueos.getValueAt(fila, 0));
                LocalDate fecha = (LocalDate) tblBloqueos.getValueAt(fila, 1);
                spnFecha.setValue(Date.from(fecha.atStartOfDay(ZoneId.systemDefault()).toInstant()));
                String horaStr = (String) tblBloqueos.getValueAt(fila, 2);
                spnHora.setValue(java.sql.Time.valueOf(horaStr));
                LocalDateTime fchCreacion = (LocalDateTime) tblBloqueos.getValueAt(fila, 3);
                spnFecha_creacion.setValue(Date.from(fchCreacion.atZone(ZoneId.systemDefault()).toInstant()));
                TXTMotivo.setText((String)tblBloqueos.getValueAt(fila, 4));
                btnModificar.setEnabled(true);
                btnEliminar.setEnabled(true);
            }
        }
    }//GEN-LAST:event_tblBloqueosMouseClicked

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        llenarTablaConBusqueda(TXTBuscarBloqueos.getText());
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void TXTBuscarBloqueosFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TXTBuscarBloqueosFocusGained
        // TODO add your handling code here:
        if (TXTBuscarBloqueos.getText().equals("Escribe el texto a buscar")){
            TXTBuscarBloqueos.setText("");
        }
    }//GEN-LAST:event_TXTBuscarBloqueosFocusGained

    private void TXTBuscarBloqueosFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TXTBuscarBloqueosFocusLost
        // TODO add your handling code here:
        if (TXTBuscarBloqueos.getText().isEmpty()){
            TXTBuscarBloqueos.setText("Escribe el texto a buscar");
        }
    }//GEN-LAST:event_TXTBuscarBloqueosFocusLost

    private Bloqueos obtenerBloqueos(){
    Bloqueos elBloqueos = new Bloqueos();
    elBloqueos.setIdbloqueo((Integer) TXTIdBloqueos.getValue());
    Date fechaDate = (Date) spnFecha.getValue();
    elBloqueos.setFecha(fechaDate.toInstant().atZone(ZoneId.systemDefault()).toLocalDate());
    Date horaDate = (Date) spnHora.getValue();
    elBloqueos.setHora_inicio(String.format("%02d:%02d:%02d",
            horaDate.getHours(), horaDate.getMinutes(), horaDate.getSeconds()));
    Date fechaCreacionDate = (Date) spnFecha_creacion.getValue();
    elBloqueos.setFecha_creacion(fechaCreacionDate.toInstant().atZone(ZoneId.systemDefault()).toLocalDateTime());
    elBloqueos.setMotivo(TXTMotivo.getText());
    return elBloqueos;
}
    private void llenarTablaConBusqueda(String busqueda){
    Bloqueos unBloqueos = new Bloqueos();
    DefaultTableModel tabla = (DefaultTableModel)tblBloqueos.getModel();
    Iterator<Bloqueos> itBloqueos = unBloqueos.buscar(busqueda);
    Object[] filaBloqueos = new Object[tblBloqueos.getColumnCount()];
    tabla.setRowCount(0); 
    while (itBloqueos.hasNext()) {
    unBloqueos = itBloqueos.next();
    filaBloqueos[0] = unBloqueos.getIdbloqueo();
    filaBloqueos[1] = unBloqueos.getFecha();
    filaBloqueos[2] = unBloqueos.getHora_inicio();
    filaBloqueos[3] = unBloqueos.getFecha_creacion();
    filaBloqueos[4] = unBloqueos.getMotivo();
    filaBloqueos[5] = unBloqueos.getCreated_at();
    ((DefaultTableModel)tblBloqueos.getModel()).addRow(filaBloqueos);
}
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TXTBuscarBloqueos;
    private javax.swing.JFormattedTextField TXTIdBloqueos;
    private javax.swing.JTextField TXTMotivo;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnInsertar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner spnCreado_por;
    private javax.swing.JSpinner spnFecha;
    private javax.swing.JSpinner spnFecha_creacion;
    private javax.swing.JSpinner spnHora;
    private javax.swing.JTable tblBloqueos;
    // End of variables declaration//GEN-END:variables
}
