/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;
import controlador.ControladorCatalogo_precios; 
import modelo.Catalogo_Precios;             
import javax.swing.table.DefaultTableModel;
import java.util.Iterator;
import java.util.Date;
import java.time.LocalDateTime;
import java.time.ZoneId;

public class FRMCatalogo_Precios extends javax.swing.JInternalFrame {
    ControladorCatalogo_precios catalogo_preciosController = new ControladorCatalogo_precios();

    /**
     * Creates new form FRMCatalogo_Precios
     */
    public FRMCatalogo_Precios() {
        initComponents();
        TXTIdCatalogo_precios.setValue(0);
        TXTIdCatalogo_precios.setVisible(false);
        limpiarFormulario();
    }
    private void limpiarFormulario() {
    TXTIdCatalogo_precios.setValue(0);
    TXTNombre.setText("Escribe nombre");
    TXTDescripcion.setText("Escribe descripcion");
    spnPrecio.setValue(0);
    TXTCategoria.setText("Escribe categoria");
    spnFecha_creacion.setValue(0);
    TXTBuscarCatalogo.setText("Escribe texto a buscar");
    btnModificar.setEnabled(false);
    btnEliminar.setEnabled(false);
    llenarTabla();
}
    public void llenarTabla(){
    Catalogo_Precios unCatalogo_Precios = new Catalogo_Precios();
    DefaultTableModel tabla = (DefaultTableModel)tblCatalogo_precios.getModel();
    Iterator<Catalogo_Precios> itCatalogo_Precios = unCatalogo_Precios.listar();
    Object[] filaCatalogo_Precios = new Object[tblCatalogo_precios.getColumnCount()];
    tabla.setRowCount(0); 
    while (itCatalogo_Precios.hasNext()) { 
        unCatalogo_Precios = itCatalogo_Precios.next();
        filaCatalogo_Precios[0] = unCatalogo_Precios.getIdcatalogo();
        filaCatalogo_Precios[1] = unCatalogo_Precios.getNombre();
        filaCatalogo_Precios[2] = unCatalogo_Precios.getDescripcion();
        filaCatalogo_Precios[3] = unCatalogo_Precios.getPrecio();
        filaCatalogo_Precios[4] = unCatalogo_Precios.getCategoria();
        filaCatalogo_Precios[5] = unCatalogo_Precios.getFechaCreacion();
        tabla.addRow(filaCatalogo_Precios);
    }
    
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLimpiar = new javax.swing.JButton();
        btnInsertar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TXTIdCatalogo_precios = new javax.swing.JFormattedTextField();
        TXTNombre = new javax.swing.JTextField();
        spnPrecio = new javax.swing.JSpinner();
        spnFecha_creacion = new javax.swing.JSpinner();
        TXTDescripcion = new javax.swing.JTextField();
        TXTCategoria = new javax.swing.JTextField();
        TXTBuscarCatalogo = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCatalogo_precios = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("                                           Formulario de Catalogo_Precios");

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(this::btnLimpiarActionPerformed);

        btnInsertar.setText("Insertar");
        btnInsertar.addActionListener(this::btnInsertarActionPerformed);

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(this::btnModificarActionPerformed);

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(this::btnEliminarActionPerformed);

        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(this::btnCerrarActionPerformed);

        jLabel1.setText("Nombre");

        jLabel2.setText("Descripcion");

        jLabel3.setText("Precio");

        jLabel4.setText("Categoria");

        jLabel5.setText("Fecha_creacion");

        jLabel6.setText("Buscar");

        TXTNombre.setText("Escribe nombre");

        spnPrecio.setModel(new javax.swing.SpinnerNumberModel(0.0f, null, null, 1.0f));

        spnFecha_creacion.setModel(new javax.swing.SpinnerDateModel());

        TXTDescripcion.setText("Escribe descripcion");

        TXTCategoria.setText("Escribe categoria");

        TXTBuscarCatalogo.setText("Escribe texto a buscar");
        TXTBuscarCatalogo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TXTBuscarCatalogoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TXTBuscarCatalogoFocusLost(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(this::btnBuscarActionPerformed);

        tblCatalogo_precios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Nombre", "Descripcion", "Precio", "Categoria", "Fecha_creacion"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblCatalogo_precios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCatalogo_preciosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCatalogo_precios);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(40, 40, 40)
                                .addComponent(TXTNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(TXTIdCatalogo_precios, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TXTDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(spnFecha_creacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TXTCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(spnPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(TXTBuscarCatalogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnBuscar)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCerrar)
                            .addComponent(btnEliminar)
                            .addComponent(btnModificar)
                            .addComponent(btnInsertar)
                            .addComponent(btnLimpiar))
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 526, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnLimpiar)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(TXTNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(TXTIdCatalogo_precios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInsertar)
                    .addComponent(jLabel2)
                    .addComponent(TXTDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnModificar)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(spnPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminar)
                    .addComponent(jLabel4)
                    .addComponent(TXTCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCerrar)
                    .addComponent(jLabel5)
                    .addComponent(spnFecha_creacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(TXTBuscarCatalogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
         limpiarFormulario();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarActionPerformed
        // TODO add your handling code here:
        catalogo_preciosController.controlarAccion(evt, obtenerCatalogo_Precios());
        limpiarFormulario();
    }//GEN-LAST:event_btnInsertarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
         catalogo_preciosController.controlarAccion(evt, obtenerCatalogo_Precios());
        limpiarFormulario();
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
         catalogo_preciosController.controlarAccion(evt, obtenerCatalogo_Precios());
        limpiarFormulario();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        // TODO add your handling code here:
        doDefaultCloseAction();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void tblCatalogo_preciosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCatalogo_preciosMouseClicked
        // TODO add your handling code here:
        if(evt.getClickCount()==2){
            int fila = tblCatalogo_precios.rowAtPoint(evt.getPoint());
            if(fila>-1){
                TXTIdCatalogo_precios.setValue((Integer)tblCatalogo_precios.getValueAt(fila, 0));
                TXTNombre.setText((String)tblCatalogo_precios.getValueAt(fila, 1));
                TXTDescripcion.setText((String)tblCatalogo_precios.getValueAt(fila, 2));
                LocalDateTime ldt = (LocalDateTime) tblCatalogo_precios.getValueAt(fila, 3);
                spnPrecio.setValue(Date.from(ldt.atZone(ZoneId.systemDefault()).toInstant())); 
                TXTCategoria.setText((String)tblCatalogo_precios.getValueAt(fila, 4));
                LocalDateTime ldt = (LocalDateTime) tblCatalogo_precios.getValueAt(fila, 5);
                spnFecha_creacion.setValue(Date.from(ldt.atZone(ZoneId.systemDefault()).toInstant()));
                btnModificar.setEnabled(true);
                btnEliminar.setEnabled(true);
            }
        }
    }//GEN-LAST:event_tblCatalogo_preciosMouseClicked

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        llenarTablaConBusqueda(TXTBuscarCatalogo.getText());
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void TXTBuscarCatalogoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TXTBuscarCatalogoFocusGained
        // TODO add your handling code here:
        if (TXTBuscarCatalogo.getText().equals("Escribe texto a buscar")){
            TXTBuscarCatalogo.setText("");
        }
    }//GEN-LAST:event_TXTBuscarCatalogoFocusGained

    private void TXTBuscarCatalogoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TXTBuscarCatalogoFocusLost
        // TODO add your handling code here:
        if (TXTBuscarCatalogo.getText().isEmpty()){
            TXTBuscarCatalogo.setText("Escribe texto a buscar");
        }
    }//GEN-LAST:event_TXTBuscarCatalogoFocusLost
 
    private Catalogo_Precios obtenerCatalogo_Precios(){
    Catalogo_Precios elCatalogo_Precios = new Catalogo_Precios();
    elCatalogo_Precios.setIdcatalogo((Integer) TXTIdCatalogo_precios.getValue());
    elCatalogo_Precios.setNombre( TXTNombre.getText());
    elCatalogo_Precios.setDescripcion( TXTDescripcion.getText());
    Date date = (Date) spnPrecio.getValue();
    elCatalogo_Precios.setCategoria( TXTCategoria.getText());
    Date date = (Date) spnFecha_creacion.getValue();
    return elCatalogo_Precios;
}
    private void llenarTablaConBusqueda(String busqueda){
    Catalogo_Precios unCatalogo_Precios = new Catalogo_Precios();
    DefaultTableModel tabla = (DefaultTableModel)tblCatalogo_precios.getModel();
    Iterator<Catalogo_Precios> itCatalogo_Precios = unCatalogo_Precios.buscar(busqueda);
    Object[] filaCatalogo_Precios = new Object[tblCatalogo_precios.getColumnCount()];
    tabla.setRowCount(0); 
    while (itCatalogo_Precios.hasNext()) {
    unCatalogo_Precios = itCatalogo_Precios.next();
    filaCatalogo_Precios[0] = unCatalogo_Precios.getIdcatalogo();
    filaCatalogo_Precios[1] = unCatalogo_Precios.getNombre();
    filaCatalogo_Precios[2] = unCatalogo_Precios.getDescripcion();
    filaCatalogo_Precios[3] = unCatalogo_Precios.getPrecio();
    filaCatalogo_Precios[4] = unCatalogo_Precios.getCategoria();
    filaCatalogo_Precios[5] = unCatalogo_Precios.getFechaCreacion();
    ((DefaultTableModel)tblCatalogo_precios.getModel()).addRow(filaCatalogo_Precios);
}
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TXTBuscarCatalogo;
    private javax.swing.JTextField TXTCategoria;
    private javax.swing.JTextField TXTDescripcion;
    private javax.swing.JFormattedTextField TXTIdCatalogo_precios;
    private javax.swing.JTextField TXTNombre;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnInsertar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner spnFecha_creacion;
    private javax.swing.JSpinner spnPrecio;
    private javax.swing.JTable tblCatalogo_precios;
    // End of variables declaration//GEN-END:variables
}
