/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;
import controlador.ControladorCatalogo_precios; 
import modelo.Catalogo_Precios;             
import javax.swing.table.DefaultTableModel;
import java.util.Iterator;
import java.util.Date;
import java.time.LocalDateTime;
import java.time.ZoneId;

public class FRMCatalogo_Precios extends javax.swing.JInternalFrame {
    ControladorCatalogo_precios catalogo_preciosController = new ControladorCatalogo_precios();

    /**
     * Creates new form FRMCatalogo_Precios
     */
    public FRMCatalogo_Precios() {
        initComponents();
        TXTIdCatalogo_precios.setValue(0);
        TXTIdCatalogo_precios.setVisible(false);
        limpiarFormulario();
    }
    private void limpiarFormulario() {
    TXTIdCatalogo_precios.setValue(0);
    TXTNombre.setText("Escribe nombre");
    TXTDescripcion.setText("Escribe descripcion");
    spnPrecio.setValue(0.0);
    TXTCategoria.setText("Escribe categoria");
    spnFecha_creacion.setValue(new java.util.Date());
    TXTBuscarCatalogo.setText("Escribe texto a buscar");
    btnModificar.setEnabled(false);
    btnEliminar.setEnabled(false);
    llenarTabla();
}
    public void llenarTabla(){
    Catalogo_Precios unCatalogo_Precios = new Catalogo_Precios();
    DefaultTableModel tabla = (DefaultTableModel)tblCatalogo_precios.getModel();
    Iterator<Catalogo_Precios> itCatalogo_Precios = unCatalogo_Precios.listar();
    Object[] filaCatalogo_Precios = new Object[tblCatalogo_precios.getColumnCount()];
    tabla.setRowCount(0); 
    while (itCatalogo_Precios.hasNext()) { 
        unCatalogo_Precios = itCatalogo_Precios.next();
        filaCatalogo_Precios[0] = unCatalogo_Precios.getIdcatalogo();
        filaCatalogo_Precios[1] = unCatalogo_Precios.getNombre();
        filaCatalogo_Precios[2] = unCatalogo_Precios.getDescripcion();
        filaCatalogo_Precios[3] = unCatalogo_Precios.getPrecio();
        filaCatalogo_Precios[4] = unCatalogo_Precios.getCategoria();
        filaCatalogo_Precios[5] = unCatalogo_Precios.getFechaCreacion();
        tabla.addRow(filaCatalogo_Precios);
    }
    
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnLimpiar = new javax.swing.JButton();
        btnInsertar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        TXTNombre = new javax.swing.JTextField();
        TXTDescripcion = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        spnPrecio = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        TXTCategoria = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        spnFecha_creacion = new javax.swing.JSpinner();
        TXTBuscarCatalogo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TXTIdCatalogo_precios = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCatalogo_precios = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("                                           Formulario de Catalogo_Precios");

        jPanel1.setBackground(new java.awt.Color(203, 178, 253));

        btnLimpiar.setBackground(new java.awt.Color(204, 204, 255));
        btnLimpiar.setFont(new java.awt.Font("Tw Cen MT", 2, 14)); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 0, 255)));
        btnLimpiar.addActionListener(this::btnLimpiarActionPerformed);

        btnInsertar.setBackground(new java.awt.Color(204, 204, 255));
        btnInsertar.setFont(new java.awt.Font("Tw Cen MT", 2, 14)); // NOI18N
        btnInsertar.setText("Insertar");
        btnInsertar.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 0, 255)));
        btnInsertar.addActionListener(this::btnInsertarActionPerformed);

        btnModificar.setBackground(new java.awt.Color(204, 204, 255));
        btnModificar.setFont(new java.awt.Font("Tw Cen MT", 2, 14)); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 0, 255)));
        btnModificar.addActionListener(this::btnModificarActionPerformed);

        btnEliminar.setBackground(new java.awt.Color(204, 204, 255));
        btnEliminar.setFont(new java.awt.Font("Tw Cen MT", 2, 14)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 0, 255)));
        btnEliminar.addActionListener(this::btnEliminarActionPerformed);

        btnCerrar.setBackground(new java.awt.Color(204, 204, 255));
        btnCerrar.setFont(new java.awt.Font("Tw Cen MT", 2, 14)); // NOI18N
        btnCerrar.setText("Cerrar");
        btnCerrar.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 0, 255)));
        btnCerrar.addActionListener(this::btnCerrarActionPerformed);

        btnBuscar.setBackground(new java.awt.Color(204, 204, 255));
        btnBuscar.setFont(new java.awt.Font("Tw Cen MT", 2, 14)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 0, 255)));
        btnBuscar.addActionListener(this::btnBuscarActionPerformed);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jLabel1.setText("Nombre");

        TXTNombre.setBackground(new java.awt.Color(233, 218, 249));
        TXTNombre.setText("Escribe nombre");

        TXTDescripcion.setBackground(new java.awt.Color(228, 203, 252));
        TXTDescripcion.setText("Escribe descripcion");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jLabel2.setText("Descripcion");

        spnPrecio.setModel(new javax.swing.SpinnerNumberModel(0.0f, null, null, 1.0f));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jLabel3.setText("Precio");

        TXTCategoria.setBackground(new java.awt.Color(232, 213, 250));
        TXTCategoria.setText("Escribe categoria");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jLabel4.setText("Categoria");

        spnFecha_creacion.setModel(new javax.swing.SpinnerDateModel());

        TXTBuscarCatalogo.setBackground(new java.awt.Color(231, 210, 252));
        TXTBuscarCatalogo.setText("Escribe texto a buscar");
        TXTBuscarCatalogo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TXTBuscarCatalogoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TXTBuscarCatalogoFocusLost(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jLabel5.setText("Fecha_creacion");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jLabel6.setText("Buscar");

        TXTIdCatalogo_precios.setBackground(new java.awt.Color(234, 214, 255));

        tblCatalogo_precios.setBackground(new java.awt.Color(232, 209, 255));
        tblCatalogo_precios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Nombre", "Descripcion", "Precio", "Categoria", "Fecha_creacion"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblCatalogo_precios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCatalogo_preciosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCatalogo_precios);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(spnFecha_creacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(22, 22, 22)
                                        .addComponent(TXTCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(222, 222, 222)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                                    .addComponent(btnCerrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(spnPrecio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(TXTNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(24, 24, 24)
                                        .addComponent(TXTIdCatalogo_precios, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(TXTDescripcion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnInsertar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnLimpiar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnModificar, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE))))
                        .addGap(22, 22, 22))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(36, 36, 36)
                        .addComponent(TXTBuscarCatalogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addComponent(jScrollPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(TXTNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(TXTIdCatalogo_precios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(TXTDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnInsertar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(TXTCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(spnFecha_creacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(TXTBuscarCatalogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(spnPrecio, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                            .addComponent(btnModificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(76, 76, 76)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
         limpiarFormulario();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarActionPerformed
        // TODO add your handling code here:
        catalogo_preciosController.controlarAccion(evt, obtenerCatalogo_Precios());
        limpiarFormulario();
    }//GEN-LAST:event_btnInsertarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
         catalogo_preciosController.controlarAccion(evt, obtenerCatalogo_Precios());
        limpiarFormulario();
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
         catalogo_preciosController.controlarAccion(evt, obtenerCatalogo_Precios());
        limpiarFormulario();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        // TODO add your handling code here:
        doDefaultCloseAction();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void tblCatalogo_preciosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCatalogo_preciosMouseClicked
        // TODO add your handling code here:
        if(evt.getClickCount()==2){
            int fila = tblCatalogo_precios.rowAtPoint(evt.getPoint());
            if(fila>-1){
                TXTIdCatalogo_precios.setValue((Integer)tblCatalogo_precios.getValueAt(fila, 0));
                TXTNombre.setText((String)tblCatalogo_precios.getValueAt(fila, 1));
                TXTDescripcion.setText((String)tblCatalogo_precios.getValueAt(fila, 2));
                spnPrecio.setValue(tblCatalogo_precios.getValueAt(fila, 3));
                TXTCategoria.setText((String)tblCatalogo_precios.getValueAt(fila, 4));
                LocalDateTime ldt = (LocalDateTime) tblCatalogo_precios.getValueAt(fila, 5);
                spnFecha_creacion.setValue(Date.from(ldt.atZone(ZoneId.systemDefault()).toInstant()));
                btnModificar.setEnabled(true);
                btnEliminar.setEnabled(true);
            }
        }
    }//GEN-LAST:event_tblCatalogo_preciosMouseClicked

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        llenarTablaConBusqueda(TXTBuscarCatalogo.getText());
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void TXTBuscarCatalogoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TXTBuscarCatalogoFocusGained
        // TODO add your handling code here:
        if (TXTBuscarCatalogo.getText().equals("Escribe texto a buscar")){
            TXTBuscarCatalogo.setText("");
        }
    }//GEN-LAST:event_TXTBuscarCatalogoFocusGained

    private void TXTBuscarCatalogoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TXTBuscarCatalogoFocusLost
        // TODO add your handling code here:
        if (TXTBuscarCatalogo.getText().isEmpty()){
            TXTBuscarCatalogo.setText("Escribe texto a buscar");
        }
    }//GEN-LAST:event_TXTBuscarCatalogoFocusLost
 
    private Catalogo_Precios obtenerCatalogo_Precios(){
    Catalogo_Precios elCatalogo_Precios = new Catalogo_Precios();
    elCatalogo_Precios.setIdcatalogo((Integer) TXTIdCatalogo_precios.getValue());
    elCatalogo_Precios.setNombre(TXTNombre.getText());
    elCatalogo_Precios.setDescripcion(TXTDescripcion.getText());
    elCatalogo_Precios.setPrecio(((Number) spnPrecio.getValue()).doubleValue());
    elCatalogo_Precios.setCategoria(TXTCategoria.getText());
    Date date = (Date) spnFecha_creacion.getValue();
    elCatalogo_Precios.setFechaCreacion(date.toInstant().atZone(ZoneId.systemDefault()).toLocalDateTime());
    return elCatalogo_Precios;
}
    private void llenarTablaConBusqueda(String busqueda){
    Catalogo_Precios unCatalogo_Precios = new Catalogo_Precios();
    DefaultTableModel tabla = (DefaultTableModel)tblCatalogo_precios.getModel();
    Iterator<Catalogo_Precios> itCatalogo_Precios = unCatalogo_Precios.buscar(busqueda);
    Object[] filaCatalogo_Precios = new Object[tblCatalogo_precios.getColumnCount()];
    tabla.setRowCount(0); 
    while (itCatalogo_Precios.hasNext()) {
    unCatalogo_Precios = itCatalogo_Precios.next();
    filaCatalogo_Precios[0] = unCatalogo_Precios.getIdcatalogo();
    filaCatalogo_Precios[1] = unCatalogo_Precios.getNombre();
    filaCatalogo_Precios[2] = unCatalogo_Precios.getDescripcion();
    filaCatalogo_Precios[3] = unCatalogo_Precios.getPrecio();
    filaCatalogo_Precios[4] = unCatalogo_Precios.getCategoria();
    filaCatalogo_Precios[5] = unCatalogo_Precios.getFechaCreacion();
    ((DefaultTableModel)tblCatalogo_precios.getModel()).addRow(filaCatalogo_Precios);
}
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TXTBuscarCatalogo;
    private javax.swing.JTextField TXTCategoria;
    private javax.swing.JTextField TXTDescripcion;
    private javax.swing.JFormattedTextField TXTIdCatalogo_precios;
    private javax.swing.JTextField TXTNombre;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnInsertar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner spnFecha_creacion;
    private javax.swing.JSpinner spnPrecio;
    private javax.swing.JTable tblCatalogo_precios;
    // End of variables declaration//GEN-END:variables
}
