/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;

import modelo.ConexionBD;

/**
 *
 * @author USUARIO
 */
public class FRMdas_clien extends javax.swing.JInternalFrame {
FRMpeluqueria fpeluqueria;
FRMtratamiento ftratamiento;
FRMmanicure fmanicure;
FRMCronograma Fcronograma;
    /**
     * Creates new form FRMdas_clien
     */
    private MDISalon padre;
    public FRMdas_clien(MDISalon padre) {
        this.padre = padre;
        initComponents();
        fpeluqueria =new FRMpeluqueria();
        ftratamiento=new FRMtratamiento();
        fmanicure=new FRMmanicure();
        Fcronograma=new FRMCronograma();
          
        
        escritorio.add(fpeluqueria);
        escritorio.add(ftratamiento);
        escritorio.add(fmanicure);
        escritorio.add(Fcronograma);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        escritorio = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnmiscitas = new javax.swing.JButton();
        panelPeluqueria = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        panelTratamiento = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        panelManicure = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jMenuItem1.setText("jMenuItem1");

        escritorio.setBackground(new java.awt.Color(255, 204, 204));

        jLabel1.setFont(new java.awt.Font("Bookman Old Style", 3, 36)); // NOI18N
        jLabel1.setText("Reserva Tu Estilo");

        jLabel2.setFont(new java.awt.Font("Monotype Corsiva", 2, 18)); // NOI18N
        jLabel2.setText("Gestiona tus citas con la delicadeza que mereces.");

        btnmiscitas.setBackground(new java.awt.Color(255, 153, 204));
        btnmiscitas.setText("Mis Citas");
        btnmiscitas.addActionListener(this::btnmiscitasActionPerformed);

        panelPeluqueria.setBackground(new java.awt.Color(255, 182, 242));
        panelPeluqueria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelPeluqueriaMouseClicked(evt);
            }
        });

        jLabel4.setText("jLabel4");

        jLabel5.setText("Peluqueria");

        jLabel6.setText("estilos");

        javax.swing.GroupLayout panelPeluqueriaLayout = new javax.swing.GroupLayout(panelPeluqueria);
        panelPeluqueria.setLayout(panelPeluqueriaLayout);
        panelPeluqueriaLayout.setHorizontalGroup(
            panelPeluqueriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPeluqueriaLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(panelPeluqueriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        panelPeluqueriaLayout.setVerticalGroup(
            panelPeluqueriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPeluqueriaLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(25, 25, 25)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        panelTratamiento.setBackground(new java.awt.Color(204, 255, 255));
        panelTratamiento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelTratamientoMouseClicked(evt);
            }
        });

        jLabel7.setText("jLabel7");

        jLabel8.setText("Tratamiento");

        jLabel9.setText("jLabel9");

        javax.swing.GroupLayout panelTratamientoLayout = new javax.swing.GroupLayout(panelTratamiento);
        panelTratamiento.setLayout(panelTratamientoLayout);
        panelTratamientoLayout.setHorizontalGroup(
            panelTratamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTratamientoLayout.createSequentialGroup()
                .addGroup(panelTratamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTratamientoLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(panelTratamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)))
                    .addGroup(panelTratamientoLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel9)))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        panelTratamientoLayout.setVerticalGroup(
            panelTratamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTratamientoLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addGap(30, 30, 30)
                .addComponent(jLabel9)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        panelManicure.setBackground(new java.awt.Color(153, 255, 204));
        panelManicure.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelManicureMouseClicked(evt);
            }
        });

        jLabel10.setText("jLabel10");

        jLabel11.setText("Manicure");

        jLabel12.setText("jLabel12");

        javax.swing.GroupLayout panelManicureLayout = new javax.swing.GroupLayout(panelManicure);
        panelManicure.setLayout(panelManicureLayout);
        panelManicureLayout.setHorizontalGroup(
            panelManicureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelManicureLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(panelManicureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        panelManicureLayout.setVerticalGroup(
            panelManicureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelManicureLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Segoe Script", 0, 18)); // NOI18N
        jLabel3.setText("Nuestros Servicios");

        jButton1.setBackground(new java.awt.Color(255, 204, 204));
        jButton1.setText("Cerrar Sesion");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        escritorio.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(btnmiscitas, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(panelPeluqueria, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(panelTratamiento, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(panelManicure, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(escritorioLayout.createSequentialGroup()
                .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(escritorioLayout.createSequentialGroup()
                        .addGap(221, 221, 221)
                        .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(escritorioLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1)))
                    .addGroup(escritorioLayout.createSequentialGroup()
                        .addGap(354, 354, 354)
                        .addComponent(btnmiscitas, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, escritorioLayout.createSequentialGroup()
                .addGap(0, 100, Short.MAX_VALUE)
                .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, escritorioLayout.createSequentialGroup()
                        .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(escritorioLayout.createSequentialGroup()
                                .addComponent(panelPeluqueria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(67, 67, 67)
                                .addComponent(panelTratamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3))
                        .addGap(50, 50, 50)
                        .addComponent(panelManicure, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(89, 89, 89))))
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(escritorioLayout.createSequentialGroup()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(btnmiscitas, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jLabel3)
                .addGap(29, 29, 29)
                .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelManicure, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelTratamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelPeluqueria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void panelPeluqueriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelPeluqueriaMouseClicked
          fpeluqueria.setVisible(true);
            fpeluqueria.toFront();
            try { 
                fpeluqueria.setSelected(true); 
            } catch (java.beans.PropertyVetoException e) {
                System.err.println("Error al enfocar: " + e.getMessage());
            }
    }//GEN-LAST:event_panelPeluqueriaMouseClicked

    private void panelTratamientoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelTratamientoMouseClicked
          ftratamiento.setVisible(true);
            ftratamiento.toFront();
            try { 
                ftratamiento.setSelected(true); 
            } catch (java.beans.PropertyVetoException e) {
                System.err.println("Error al enfocar: " + e.getMessage());
            }
    }//GEN-LAST:event_panelTratamientoMouseClicked

    private void panelManicureMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelManicureMouseClicked
           fmanicure.setVisible(true);
            fmanicure.toFront();
            try { 
                fmanicure.setSelected(true); 
            } catch (java.beans.PropertyVetoException e) {
                System.err.println("Error al enfocar: " + e.getMessage());
            }
    }//GEN-LAST:event_panelManicureMouseClicked

    private void btnmiscitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmiscitasActionPerformed
        Fcronograma.setVisible(true);
    }//GEN-LAST:event_btnmiscitasActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       regresarAlLogin();
       this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
private void regresarAlLogin() {
    ConexionBD.desconectar();
    padre.mostrarLogin();
    this.dispose();
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnmiscitas;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel panelManicure;
    private javax.swing.JPanel panelPeluqueria;
    private javax.swing.JPanel panelTratamiento;
    // End of variables declaration//GEN-END:variables
}
