/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;
import modelo.ConexionBD;
/**
 *
 * @author USUARIO
 */
public class FRMdas_admin extends javax.swing.JInternalFrame {
  FRMUsuario fUsuario;
   FRMServicios fServicio;
   FRMProductos fProducto;
//   FRMProveedores fProveedores;
   FRMInventario fInventario;
    FRMPerfiles fPerfiles;
    FRMCitas fCita;
    FRMCatalogo_Precios fCatalogo;
    FRMBloqueos fBloqueos;
    FRMAgenda FAgenda;
    /**
     * Creates new form dasadmin
     */
    private javax.swing.JFrame loginPrincipal;
    public FRMdas_admin() {
        initComponents(); 
    this.loginPrincipal = loginPrincipal;
        fUsuario = new FRMUsuario();
        fServicio=new FRMServicios();
        fProducto=new FRMProductos();
//        fProveedores=new FRMProveedores();
        fInventario=new FRMInventario();
        fPerfiles=new FRMPerfiles();
        fCita=new FRMCitas();
        fCatalogo=new FRMCatalogo_Precios();
        fBloqueos=new FRMBloqueos();
        FAgenda=new FRMAgenda();
        
        escritorio.add(fUsuario);
        escritorio.add(fServicio);
        escritorio.add(fProducto);
        escritorio.add(fPerfiles);
        escritorio.add(fCita);
        escritorio.add(fCatalogo);
        escritorio.add(fBloqueos);
        escritorio.add(FAgenda);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        escritorio = new javax.swing.JDesktopPane();
        PanelCitas = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        PanelServicios = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        PanelProductos = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        PanelProveedores = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        PanelInventario = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        PanelAgenda = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        btnGestionUsuario = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuInicio = new javax.swing.JMenu();
        MenuCatalogo = new javax.swing.JMenu();
        menuBloqueos = new javax.swing.JMenu();
        menuCerrar = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenuItem3.setText("jMenuItem3");

        setTitle("SALON GLITT");

        escritorio.setBackground(new java.awt.Color(255, 224, 245));

        PanelCitas.setBackground(new java.awt.Color(255, 204, 204));
        PanelCitas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelCitasMouseClicked(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\USUARIO\\Pictures\\Screenshots\\Captura de pantalla 2026-06-28 152349.png")); // NOI18N

        jLabel4.setText("Citas");

        javax.swing.GroupLayout PanelCitasLayout = new javax.swing.GroupLayout(PanelCitas);
        PanelCitas.setLayout(PanelCitasLayout);
        PanelCitasLayout.setHorizontalGroup(
            PanelCitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCitasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        PanelCitasLayout.setVerticalGroup(
            PanelCitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCitasLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelCitasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        escritorio.add(PanelCitas);
        PanelCitas.setBounds(260, 190, 160, 90);

        PanelServicios.setBackground(new java.awt.Color(153, 255, 204));
        PanelServicios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelServiciosMouseClicked(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\USUARIO\\Pictures\\Screenshots\\Captura de pantalla 2026-06-28 153627.png")); // NOI18N

        jLabel2.setText("Servicios");

        javax.swing.GroupLayout PanelServiciosLayout = new javax.swing.GroupLayout(PanelServicios);
        PanelServicios.setLayout(PanelServiciosLayout);
        PanelServiciosLayout.setHorizontalGroup(
            PanelServiciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelServiciosLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addContainerGap(53, Short.MAX_VALUE))
        );
        PanelServiciosLayout.setVerticalGroup(
            PanelServiciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelServiciosLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(PanelServiciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelServiciosLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel2)))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        escritorio.add(PanelServicios);
        PanelServicios.setBounds(470, 180, 170, 90);

        PanelProductos.setBackground(new java.awt.Color(255, 153, 255));
        PanelProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelProductosMouseClicked(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\USUARIO\\Pictures\\Screenshots\\Captura de pantalla 2026-06-28 153643.png")); // NOI18N

        jLabel6.setText("Productos");

        javax.swing.GroupLayout PanelProductosLayout = new javax.swing.GroupLayout(PanelProductos);
        PanelProductos.setLayout(PanelProductosLayout);
        PanelProductosLayout.setHorizontalGroup(
            PanelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelProductosLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(40, 40, 40)
                .addComponent(jLabel6)
                .addGap(26, 26, 26))
        );
        PanelProductosLayout.setVerticalGroup(
            PanelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelProductosLayout.createSequentialGroup()
                .addGroup(PanelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelProductosLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel6))
                    .addGroup(PanelProductosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        escritorio.add(PanelProductos);
        PanelProductos.setBounds(700, 180, 160, 90);

        PanelProveedores.setBackground(new java.awt.Color(102, 204, 255));
        PanelProveedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelProveedoresMouseClicked(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\USUARIO\\Pictures\\Screenshots\\Captura de pantalla 2026-06-28 154057.png")); // NOI18N

        jLabel8.setText("Proveedores");

        javax.swing.GroupLayout PanelProveedoresLayout = new javax.swing.GroupLayout(PanelProveedores);
        PanelProveedores.setLayout(PanelProveedoresLayout);
        PanelProveedoresLayout.setHorizontalGroup(
            PanelProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelProveedoresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        PanelProveedoresLayout.setVerticalGroup(
            PanelProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelProveedoresLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(PanelProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelProveedoresLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel8)))
                .addGap(85, 85, 85))
        );

        escritorio.add(PanelProveedores);
        PanelProveedores.setBounds(260, 300, 160, 90);

        PanelInventario.setBackground(new java.awt.Color(255, 204, 153));
        PanelInventario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelInventarioMouseClicked(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\USUARIO\\Pictures\\Screenshots\\Captura de pantalla 2026-06-28 154102.png")); // NOI18N

        jLabel10.setText("Inventario");

        javax.swing.GroupLayout PanelInventarioLayout = new javax.swing.GroupLayout(PanelInventario);
        PanelInventario.setLayout(PanelInventarioLayout);
        PanelInventarioLayout.setHorizontalGroup(
            PanelInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelInventarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addContainerGap(54, Short.MAX_VALUE))
        );
        PanelInventarioLayout.setVerticalGroup(
            PanelInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelInventarioLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(PanelInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelInventarioLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(15, 15, 15)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        escritorio.add(PanelInventario);
        PanelInventario.setBounds(480, 300, 170, 90);

        PanelAgenda.setBackground(new java.awt.Color(255, 255, 204));
        PanelAgenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelAgendaMouseClicked(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\USUARIO\\Pictures\\Screenshots\\Captura de pantalla 2026-06-28 154107.png")); // NOI18N

        jLabel12.setText("Agenda");

        javax.swing.GroupLayout PanelAgendaLayout = new javax.swing.GroupLayout(PanelAgenda);
        PanelAgenda.setLayout(PanelAgendaLayout);
        PanelAgendaLayout.setHorizontalGroup(
            PanelAgendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAgendaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(33, 33, 33))
        );
        PanelAgendaLayout.setVerticalGroup(
            PanelAgendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAgendaLayout.createSequentialGroup()
                .addGroup(PanelAgendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelAgendaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelAgendaLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel12)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        escritorio.add(PanelAgenda);
        PanelAgenda.setBounds(700, 300, 160, 90);

        jLabel13.setFont(new java.awt.Font("SimSun-ExtG", 3, 24)); // NOI18N
        jLabel13.setText("Panel de Control");
        escritorio.add(jLabel13);
        jLabel13.setBounds(270, 80, 240, 50);

        jPanel1.setBackground(new java.awt.Color(255, 175, 215));

        jLabel14.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel14.setText("ADMIN SALON");

        btnGestionUsuario.setBackground(new java.awt.Color(255, 204, 255));
        btnGestionUsuario.setText("Gestion de Usuarios");
        btnGestionUsuario.addActionListener(this::btnGestionUsuarioActionPerformed);

        btnCerrar.setBackground(new java.awt.Color(255, 204, 255));
        btnCerrar.setText("Cerrar Sesion");
        btnCerrar.addActionListener(this::btnCerrarActionPerformed);

        jLabel15.setIcon(new javax.swing.ImageIcon("C:\\Users\\USUARIO\\Pictures\\Screenshots\\Captura de pantalla 2026-06-28 170030.png")); // NOI18N

        jLabel16.setIcon(new javax.swing.ImageIcon("C:\\Users\\USUARIO\\Pictures\\Screenshots\\Captura de pantalla 2026-06-28 170039.png")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel16)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnGestionUsuario))
                        .addGap(44, 44, 44))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnGestionUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(311, Short.MAX_VALUE))
        );

        escritorio.add(jPanel1);
        jPanel1.setBounds(0, 0, 250, 480);

        menuInicio.setText("Inicio");
        menuInicio.addActionListener(this::menuInicioActionPerformed);
        jMenuBar1.add(menuInicio);

        MenuCatalogo.setText("Catalogo");
        MenuCatalogo.addActionListener(this::MenuCatalogoActionPerformed);
        jMenuBar1.add(MenuCatalogo);

        menuBloqueos.setText("Bloqueos");
        menuBloqueos.addActionListener(this::menuBloqueosActionPerformed);
        jMenuBar1.add(menuBloqueos);

        menuCerrar.setText("Cerrar Sesion");
        jMenuBar1.add(menuCerrar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 972, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PanelCitasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelCitasMouseClicked
        fCita.setVisible(true);
            fCita.toFront();
            try { 
                fCita.setSelected(true); 
            } catch (java.beans.PropertyVetoException e) {
                System.err.println("Error al enfocar: " + e.getMessage());
            }
        
    }//GEN-LAST:event_PanelCitasMouseClicked

    private void PanelServiciosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelServiciosMouseClicked
     fServicio.setVisible(true);
                fServicio.toFront();
                try { fServicio.setSelected(true); } catch (Exception e) {}
            
    }//GEN-LAST:event_PanelServiciosMouseClicked

    private void PanelProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelProductosMouseClicked
             fProducto.setVisible(true);
            fProducto.toFront();
            try { 
                fProducto.setSelected(true); 
            } catch (java.beans.PropertyVetoException e) {
                System.err.println("Error al enfocar: " + e.getMessage());
            }
    }//GEN-LAST:event_PanelProductosMouseClicked

    private void PanelProveedoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelProveedoresMouseClicked
//          fProveedores.setVisible(true);
//            fProveedores.toFront();
//            try { 
//                fProveedores.setSelected(true); 
//            } catch (java.beans.PropertyVetoException e) {
//                System.err.println("Error al enfocar: " + e.getMessage());
//            }
    }//GEN-LAST:event_PanelProveedoresMouseClicked

    private void PanelInventarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelInventarioMouseClicked
            fInventario.setVisible(true);
            fInventario.toFront();
            try { 
                fInventario.setSelected(true); 
            } catch (java.beans.PropertyVetoException e) {
                System.err.println("Error al enfocar: " + e.getMessage());
            }
    }//GEN-LAST:event_PanelInventarioMouseClicked

    private void PanelAgendaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelAgendaMouseClicked
           FAgenda.setVisible(true);
            FAgenda.toFront();
            try { 
                FAgenda.setSelected(true); 
            } catch (java.beans.PropertyVetoException e) {
                System.err.println("Error al enfocar: " + e.getMessage());
            }
    }//GEN-LAST:event_PanelAgendaMouseClicked

private void regresarAlLogin() {
    ConexionBD.desconectar(); // Cierras base de datos
    
    if (this.loginPrincipal != null) {
        this.loginPrincipal.setVisible(true); // Volvemos a mostrar el Login
    }
    
    this.dispose(); // Cerramos la ventana actual
}
    private void menuInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuInicioActionPerformed
    regresarAlLogin();
    }//GEN-LAST:event_menuInicioActionPerformed

    private void MenuCatalogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCatalogoActionPerformed
     fCatalogo.setVisible(true);
    }//GEN-LAST:event_MenuCatalogoActionPerformed

    private void menuBloqueosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBloqueosActionPerformed
       fBloqueos.setVisible(true);
    }//GEN-LAST:event_menuBloqueosActionPerformed

    private void btnGestionUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionUsuarioActionPerformed
        fUsuario.setVisible(true);
        fUsuario.toFront();
    }//GEN-LAST:event_btnGestionUsuarioActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
       regresarAlLogin();
    }//GEN-LAST:event_btnCerrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuCatalogo;
    private javax.swing.JPanel PanelAgenda;
    private javax.swing.JPanel PanelCitas;
    private javax.swing.JPanel PanelInventario;
    private javax.swing.JPanel PanelProductos;
    private javax.swing.JPanel PanelProveedores;
    private javax.swing.JPanel PanelServicios;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnGestionUsuario;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu menuBloqueos;
    private javax.swing.JMenu menuCerrar;
    private javax.swing.JMenu menuInicio;
    // End of variables declaration//GEN-END:variables

}