/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;
import controlador.ControladorInventario; 
import modelo.Inventario;                 
import javax.swing.table.DefaultTableModel;
import java.util.Iterator;
import java.time.LocalDate;
/**
 *
 * @author LENOVO
 */
public class FRMInventario extends javax.swing.JInternalFrame {
    ControladorInventario inventarioController = new ControladorInventario();
    /**
     * Creates new form FRMInventario
     */
    public FRMInventario() {
        initComponents();
        TXTIdInventario.setValue(0);
        TXTIdInventario.setVisible(false);
        limpiarFormulario();
    }
    private void limpiarFormulario() {
    TXTIdInventario.setValue(0);
    spnStock.setValue(0);
    TXTFecha.setText("yyyy-MM-dd");
    TXTBuscarInventario.setText("Escriba texto a buscar");
    btnModificar.setEnabled(false);
    btnEliminar.setEnabled(false);
    llenarTabla();
}
    public void llenarTabla(){
    Inventario unInventario = new Inventario();
    DefaultTableModel tabla = (DefaultTableModel)tblInventario.getModel();
    Iterator<Inventario> itInventario = unInventario.listar();
    Object[] filaInventario = new Object[tblInventario.getColumnCount()];
    tabla.setRowCount(0); 
    while (itInventario.hasNext()) { 
        unInventario = itInventario.next();
        filaInventario[0] = unInventario.getIdinventario();
        filaInventario[1] = unInventario.getStock();
        filaInventario[2] = unInventario.getFecha();       
        tabla.addRow(filaInventario);
    }
    
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnInsertar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblfecha = new javax.swing.JLabel();
        TXTFecha = new javax.swing.JTextField();
        TXTIdInventario = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        TXTBuscarInventario = new javax.swing.JTextField();
        spnStock = new javax.swing.JSpinner();
        btnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblInventario = new javax.swing.JTable();
        btnLimpiar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("                                          Formulario de Inventario");

        btnInsertar.setText("Insertar");
        btnInsertar.addActionListener(this::btnInsertarActionPerformed);

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(this::btnModificarActionPerformed);

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(this::btnEliminarActionPerformed);

        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(this::btnCerrarActionPerformed);

        jLabel1.setText("Stock");

        lblfecha.setText("Fecha");

        TXTFecha.setText("Escribe la fecha");

        jLabel2.setText("Buscar");

        TXTBuscarInventario.setText("Escribe texto a buscar");
        TXTBuscarInventario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TXTBuscarInventarioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TXTBuscarInventarioFocusLost(evt);
            }
        });

        spnStock.setModel(new javax.swing.SpinnerDateModel());

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(this::btnBuscarActionPerformed);

        tblInventario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Id", "Stock", "Fecha"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblInventario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblInventarioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblInventario);

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(this::btnLimpiarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(spnStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(TXTIdInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblfecha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TXTFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TXTBuscarInventario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBuscar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCerrar)
                    .addComponent(btnEliminar)
                    .addComponent(btnModificar)
                    .addComponent(btnInsertar)
                    .addComponent(btnLimpiar))
                .addGap(32, 32, 32))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(TXTIdInventario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spnStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblfecha)
                            .addComponent(TXTFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(TXTBuscarInventario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscar))
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnLimpiar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnInsertar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminar)
                        .addGap(10, 10, 10)))
                .addComponent(btnCerrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        // TODO add your handling code here:
        doDefaultCloseAction();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarActionPerformed
        // TODO add your handling code here:
        inventarioController.controlarAccion(evt, obtenerInventario());
        limpiarFormulario();
    }//GEN-LAST:event_btnInsertarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        inventarioController.controlarAccion(evt, obtenerInventario());
        limpiarFormulario();
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        inventarioController.controlarAccion(evt, obtenerInventario());
        limpiarFormulario();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void tblInventarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblInventarioMouseClicked
        // TODO add your handling code here:
        if(evt.getClickCount()==2){
            int fila = tblInventario.rowAtPoint(evt.getPoint());
            if(fila>-1){
                TXTIdInventario.setValue((Integer)tblInventario.getValueAt(fila, 0));
                spnStock.setValue((Integer)tblInventario.getValueAt(fila, 1));
                TXTFecha.setText((String)tblInventario.getValueAt(fila, 2));
                btnModificar.setEnabled(true);
                btnEliminar.setEnabled(true);
            }
        }
    }//GEN-LAST:event_tblInventarioMouseClicked

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        llenarTablaConBusqueda(TXTBuscarInventario.getText());
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void TXTBuscarInventarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TXTBuscarInventarioFocusGained
        // TODO add your handling code here:
        if (TXTBuscarInventario.getText().equals("Escribe texto a buscar")){
            TXTBuscarInventario.setText("");
        }
    }//GEN-LAST:event_TXTBuscarInventarioFocusGained

    private void TXTBuscarInventarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TXTBuscarInventarioFocusLost
        // TODO add your handling code here:
        if (TXTBuscarInventario.getText().isEmpty()){
            TXTBuscarInventario.setText("Escribe texto a buscar");
        }
    }//GEN-LAST:event_TXTBuscarInventarioFocusLost

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        limpiarFormulario();
    }//GEN-LAST:event_btnLimpiarActionPerformed
    private Inventario obtenerInventario(){
    Inventario elInventario = new Inventario();
    elInventario.setIdinventario((Integer) TXTIdInventario.getValue());
    elInventario.setStock((Integer) spnStock.getValue());
    elInventario.setFecha(LocalDate.parse(TXTFecha.getText()));
    return elInventario;
}
    private void llenarTablaConBusqueda(String busqueda){
    Inventario unInventario = new Inventario();
    DefaultTableModel tabla = (DefaultTableModel)tblInventario.getModel();
    Iterator<Inventario> itInventario = unInventario.buscar(busqueda);
    Object[] filaInventario = new Object[tblInventario.getColumnCount()];
    tabla.setRowCount(0); 
    while (itInventario.hasNext()) {
    unInventario = itInventario.next();
    filaInventario[0] = unInventario.getIdinventario();
    filaInventario[1] = unInventario.getStock();
    filaInventario[2] = unInventario.getFecha();
    ((DefaultTableModel)tblInventario.getModel()).addRow(filaInventario);
}
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TXTBuscarInventario;
    private javax.swing.JTextField TXTFecha;
    private javax.swing.JFormattedTextField TXTIdInventario;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnInsertar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblfecha;
    private javax.swing.JSpinner spnStock;
    private javax.swing.JTable tblInventario;
    // End of variables declaration//GEN-END:variables
}
