/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;
import controlador.ControladorPerfiles; 
import modelo.Perfiles;                 
import javax.swing.table.DefaultTableModel;
import java.util.Iterator;
/**
 *
 * @author LENOVO
 */
public class FRMPerfiles extends javax.swing.JInternalFrame {
    ControladorPerfiles perfilesController = new ControladorPerfiles();

    /**
     * Creates new form FRMPerfil
     */
    public FRMPerfiles() {
        initComponents();
        TXTIdPerfil.setValue(0);
        TXTIdPerfil.setVisible(false);
        limpiarFormulario();
    }
    private void limpiarFormulario() {
    TXTIdPerfil.setValue(0);
    TXTNombre.setText("Escribe nombre");
    TXTApellido.setText("Escribe apellido"); 
    TXTBiografia.setText("Escriba biografia");
    TXTBuscarPerfiles.setText("Escribe texto a buscar");
    btnModificar.setEnabled(false);
    btnEliminar.setEnabled(false);
    llenarTabla();
}
    public void llenarTabla(){
    Perfiles unPerfil = new Perfiles();
    DefaultTableModel tabla = (DefaultTableModel)tblPerfil.getModel();
    Iterator<Perfiles> itPerfiles = unPerfil.listar();
    Object[] filaPerfiles = new Object[tblPerfil.getColumnCount()];
    tabla.setRowCount(0); 
    while (itPerfiles.hasNext()) { 
        unPerfil = itPerfiles.next();
        filaPerfiles[0] = unPerfil.getId();
        filaPerfiles[1] = unPerfil.getNombre();
        filaPerfiles[2] = unPerfil.getApellido();       
        filaPerfiles[3] = unPerfil.getBio();
        tabla.addRow(filaPerfiles);
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TXTNombre = new javax.swing.JTextField();
        TXTIdPerfil = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        TXTApellido = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TXTBiografia = new javax.swing.JTextField();
        btnLimpiar = new javax.swing.JButton();
        btnInsertar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        TXTBuscarPerfiles = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnBuscarPerfil = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPerfil = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("                                             Formulario de Perfil");

        jPanel1.setBackground(new java.awt.Color(214, 174, 253));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jLabel1.setText("Nombre");

        TXTNombre.setBackground(new java.awt.Color(233, 216, 250));
        TXTNombre.setFont(new java.awt.Font("Sylfaen", 0, 12)); // NOI18N
        TXTNombre.setText("Escribe el nombre");

        TXTIdPerfil.setBackground(new java.awt.Color(233, 215, 252));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jLabel2.setText("Apellido");

        TXTApellido.setBackground(new java.awt.Color(234, 217, 252));
        TXTApellido.setFont(new java.awt.Font("Sylfaen", 0, 12)); // NOI18N
        TXTApellido.setText("Escribe el apellido");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jLabel3.setText("Biografia");

        TXTBiografia.setBackground(new java.awt.Color(229, 209, 249));
        TXTBiografia.setFont(new java.awt.Font("Sylfaen", 0, 12)); // NOI18N
        TXTBiografia.setText("Escribe la biografia");

        btnLimpiar.setBackground(new java.awt.Color(204, 204, 255));
        btnLimpiar.setFont(new java.awt.Font("Tw Cen MT", 2, 14)); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(this::btnLimpiarActionPerformed);

        btnInsertar.setBackground(new java.awt.Color(204, 204, 255));
        btnInsertar.setFont(new java.awt.Font("Tw Cen MT", 2, 14)); // NOI18N
        btnInsertar.setText("Insertar");
        btnInsertar.addActionListener(this::btnInsertarActionPerformed);

        btnModificar.setBackground(new java.awt.Color(204, 204, 255));
        btnModificar.setFont(new java.awt.Font("Tw Cen MT", 2, 14)); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(this::btnModificarActionPerformed);

        btnEliminar.setBackground(new java.awt.Color(204, 204, 255));
        btnEliminar.setFont(new java.awt.Font("Tw Cen MT", 2, 14)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(this::btnEliminarActionPerformed);

        btnCerrar.setBackground(new java.awt.Color(204, 204, 255));
        btnCerrar.setFont(new java.awt.Font("Tw Cen MT", 2, 14)); // NOI18N
        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(this::btnCerrarActionPerformed);

        TXTBuscarPerfiles.setBackground(new java.awt.Color(235, 220, 249));
        TXTBuscarPerfiles.setFont(new java.awt.Font("Sylfaen", 0, 12)); // NOI18N
        TXTBuscarPerfiles.setText("Escribe texto a buscar");
        TXTBuscarPerfiles.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TXTBuscarPerfilesFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TXTBuscarPerfilesFocusLost(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jLabel4.setText("Buscar");

        btnBuscarPerfil.setBackground(new java.awt.Color(204, 204, 255));
        btnBuscarPerfil.setFont(new java.awt.Font("Tw Cen MT", 2, 14)); // NOI18N
        btnBuscarPerfil.setText("Buscar");
        btnBuscarPerfil.addActionListener(this::btnBuscarPerfilActionPerformed);

        tblPerfil.setBackground(new java.awt.Color(227, 206, 248));
        tblPerfil.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Nombre", "Apellido", "Bio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblPerfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPerfilMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPerfil);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(TXTNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(TXTApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(jLabel4)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TXTBiografia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(TXTBuscarPerfiles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(TXTIdPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnBuscarPerfil))))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnInsertar)
                                .addComponent(btnLimpiar))
                            .addComponent(btnModificar, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnCerrar)
                            .addComponent(btnEliminar))))
                .addGap(26, 26, 26))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 514, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TXTNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TXTIdPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpiar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TXTApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInsertar))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnModificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCerrar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TXTBiografia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TXTBuscarPerfiles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(btnBuscarPerfil))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
     // TODO add your handling code here:
               limpiarFormulario();  
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        // TODO add your handling code here:
        doDefaultCloseAction();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarActionPerformed
        // TODO add your handling code here:
        perfilesController.controlarAccion(evt, obtenerPerfiles());
        limpiarFormulario();
    }//GEN-LAST:event_btnInsertarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        perfilesController.controlarAccion(evt, obtenerPerfiles());
        limpiarFormulario();
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        perfilesController.controlarAccion(evt, obtenerPerfiles());
        limpiarFormulario();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void tblPerfilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPerfilMouseClicked
        // TODO add your handling code here:
        if(evt.getClickCount()==2){
            int fila = tblPerfil.rowAtPoint(evt.getPoint());
            if(fila>-1){
                TXTIdPerfil.setValue((Integer)tblPerfil.getValueAt(fila, 0));
                TXTNombre.setText((String)tblPerfil.getValueAt(fila, 1));
                TXTApellido.setText((String)tblPerfil.getValueAt(fila, 2));
                TXTBiografia.setText((String)tblPerfil.getValueAt(fila, 3));
                btnModificar.setEnabled(true);
                btnEliminar.setEnabled(true);
                
            }
        }
    }//GEN-LAST:event_tblPerfilMouseClicked

    private void btnBuscarPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPerfilActionPerformed
        // TODO add your handling code here:
        llenarTablaConBusqueda(TXTBuscarPerfiles.getText());
    }//GEN-LAST:event_btnBuscarPerfilActionPerformed

    private void TXTBuscarPerfilesFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TXTBuscarPerfilesFocusGained
        // TODO add your handling code here:
        if (TXTBuscarPerfiles.getText().equals("Escribe texto a buscar")){
            TXTBuscarPerfiles.setText("");
        }
    }//GEN-LAST:event_TXTBuscarPerfilesFocusGained

    private void TXTBuscarPerfilesFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TXTBuscarPerfilesFocusLost
        // TODO add your handling code here:
        if (TXTBuscarPerfiles.getText().isEmpty()){
            TXTBuscarPerfiles.setText("Escribe texto a buscar");
        }
    }//GEN-LAST:event_TXTBuscarPerfilesFocusLost

    private Perfiles obtenerPerfiles(){
    Perfiles elPerfil = new Perfiles();
    elPerfil.setId((Integer) TXTIdPerfil.getValue());
    elPerfil.setNombre( TXTNombre.getText());
    elPerfil.setApellido( TXTApellido.getText());
    elPerfil.setBio( TXTBiografia.getText());
    return elPerfil;
}
    private void llenarTablaConBusqueda(String busqueda){
    Perfiles unPerfil = new Perfiles();
    DefaultTableModel tabla = (DefaultTableModel)tblPerfil.getModel();
    Iterator<Perfiles> itPerfiles = unPerfil.buscar(busqueda);
    Object[] filaPerfiles = new Object[tblPerfil.getColumnCount()];
    tabla.setRowCount(0); 
    while (itPerfiles.hasNext()) {
    unPerfil = itPerfiles.next();
    filaPerfiles[0] = unPerfil.getId();
    filaPerfiles[1] = unPerfil.getNombre();
    filaPerfiles[2] = unPerfil.getApellido();
    filaPerfiles[3] = unPerfil.getBio();
    ((DefaultTableModel)tblPerfil.getModel()).addRow(filaPerfiles);
}
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TXTApellido;
    private javax.swing.JTextField TXTBiografia;
    private javax.swing.JTextField TXTBuscarPerfiles;
    private javax.swing.JFormattedTextField TXTIdPerfil;
    private javax.swing.JTextField TXTNombre;
    private javax.swing.JButton btnBuscarPerfil;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnInsertar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPerfil;
    // End of variables declaration//GEN-END:variables
}
