/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;
import controlador.ControladorRecordatorios; 
import modelo.Recordatorios;                 
import javax.swing.table.DefaultTableModel;
import java.util.Iterator;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
/**
 *
 * @author LENOVO
 */
public class FRMRecordatorios extends javax.swing.JInternalFrame {
    ControladorRecordatorios recordatoriosController = new ControladorRecordatorios();
    /**
     * Creates new form FRMRecordatorios
     */
    public FRMRecordatorios() {
        initComponents();
        txtIdRecordatorios.setValue(0);
        txtIdRecordatorios.setVisible(false);
        limpiarFormulario();
    }
    private void limpiarFormulario() {
    txtIdRecordatorios.setValue(0);
    txtTitulo.setText("Escribe titulo");
    txtMensaje.setText("Escribe mensaje"); 
    txtFecha.setText("Escriba fecha");
    txtBuscar.setText("Escribe texto a buscar");
    btnModificar.setEnabled(false);
    btnEliminar.setEnabled(false);
    llenarTabla();
}
    public void llenarTabla(){
    Recordatorios unRecordatorios = new Recordatorios();
    DefaultTableModel tabla = (DefaultTableModel)tblRecordatorios.getModel();
    Iterator<Recordatorios> itRecordatorios = unRecordatorios.listar();
    Object[] filaRecordatorios = new Object[tblRecordatorios.getColumnCount()];
    tabla.setRowCount(0); 
    while (itRecordatorios.hasNext()) { 
        unRecordatorios = itRecordatorios.next();
        filaRecordatorios[0] = unRecordatorios.getIdrecordatorios();
        filaRecordatorios[1] = unRecordatorios.getTitulo();
        filaRecordatorios[2] = unRecordatorios.getMensaje();       
        filaRecordatorios[3] = unRecordatorios.getFecha_recordatorio();
        tabla.addRow(filaRecordatorios);
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtIdRecordatorios = new javax.swing.JFormattedTextField();
        btnLimpiar = new javax.swing.JButton();
        btnInsertar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        txtMensaje = new javax.swing.JTextField();
        txtFecha = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRecordatorios = new javax.swing.JTable();

        setBackground(new java.awt.Color(204, 153, 255));
        setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 153, 255)));
        setClosable(true);
        setForeground(new java.awt.Color(204, 153, 255));
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("                                          Formulario de Recordatorios");
        setFont(new java.awt.Font("Cambria Math", 2, 14)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(190, 144, 252));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(171, 106, 235)));

        txtIdRecordatorios.setBackground(new java.awt.Color(233, 211, 255));

        btnLimpiar.setBackground(new java.awt.Color(204, 204, 255));
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(this::btnLimpiarActionPerformed);

        btnInsertar.setBackground(new java.awt.Color(204, 204, 255));
        btnInsertar.setText("Insertar");
        btnInsertar.addActionListener(this::btnInsertarActionPerformed);

        btnModificar.setBackground(new java.awt.Color(204, 204, 255));
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(this::btnModificarActionPerformed);

        btnEliminar.setBackground(new java.awt.Color(204, 204, 255));
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(this::btnEliminarActionPerformed);

        btnCerrar.setBackground(new java.awt.Color(204, 204, 255));
        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(this::btnCerrarActionPerformed);

        jLabel1.setText("Titulo");

        jLabel2.setText("Mensaje");

        jLabel3.setText("Fecha_recordatorio");

        txtTitulo.setBackground(new java.awt.Color(226, 197, 255));
        txtTitulo.setText("Escribe titulo");

        txtMensaje.setBackground(new java.awt.Color(228, 203, 252));
        txtMensaje.setText("Escribe mensaje");

        txtFecha.setBackground(new java.awt.Color(220, 190, 249));
        txtFecha.setText("Escribe la fecha");

        jLabel4.setText("Buscar");

        txtBuscar.setBackground(new java.awt.Color(227, 200, 255));
        txtBuscar.setText("Escribe texto a buscar");
        txtBuscar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtBuscarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtBuscarFocusLost(evt);
            }
        });

        btnBuscar.setBackground(new java.awt.Color(204, 204, 255));
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(this::btnBuscarActionPerformed);

        tblRecordatorios.setBackground(new java.awt.Color(228, 203, 252));
        tblRecordatorios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Titulo", "Mensaje", "Fecha_recordatorio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblRecordatorios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblRecordatoriosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblRecordatorios);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtIdRecordatorios, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnLimpiar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnInsertar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnModificar))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(jLabel2)
                                .addGap(3, 3, 3)
                                .addComponent(txtMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnEliminar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnCerrar))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(btnBuscar)))
                .addContainerGap(210, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdRecordatorios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpiar)
                    .addComponent(btnInsertar)
                    .addComponent(btnModificar)
                    .addComponent(btnEliminar)
                    .addComponent(btnCerrar))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        limpiarFormulario();  
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        // TODO add your handling code here:
         doDefaultCloseAction();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarActionPerformed
        // TODO add your handling code here:
        recordatoriosController.controlarAccion(evt, obtenerRecordatorios());
        limpiarFormulario();
    }//GEN-LAST:event_btnInsertarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        recordatoriosController.controlarAccion(evt, obtenerRecordatorios());
        limpiarFormulario();
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        recordatoriosController.controlarAccion(evt, obtenerRecordatorios());
        limpiarFormulario();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void tblRecordatoriosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblRecordatoriosMouseClicked
        // TODO add your handling code here:
        if(evt.getClickCount()==2){
            int fila = tblRecordatorios.rowAtPoint(evt.getPoint());
            if(fila>-1){
                txtIdRecordatorios.setValue((Integer)tblRecordatorios.getValueAt(fila, 0));
                txtTitulo.setText((String)tblRecordatorios.getValueAt(fila, 1));
                txtMensaje.setText((String)tblRecordatorios.getValueAt(fila, 2));
                Object fechaObj = tblRecordatorios.getValueAt(fila, 3);
                if (fechaObj instanceof LocalDate) {
                    txtFecha.setText(((LocalDate) fechaObj).format(DateTimeFormatter.ofPattern("yyyy-MM-dd")));
                } else if (fechaObj != null) {
                    txtFecha.setText(fechaObj.toString());
                }
                btnModificar.setEnabled(true);
                btnEliminar.setEnabled(true);
                
            }
        }
    }//GEN-LAST:event_tblRecordatoriosMouseClicked

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        llenarTablaConBusqueda(txtBuscar.getText());
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txtBuscarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBuscarFocusGained
        // TODO add your handling code here:
         if (txtBuscar.getText().equals("Escribe texto a buscar")){
            txtBuscar.setText("");
        }
    }//GEN-LAST:event_txtBuscarFocusGained

    private void txtBuscarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBuscarFocusLost
        // TODO add your handling code here:
        if (txtBuscar.getText().isEmpty()){
            txtBuscar.setText("Escribe texto a buscar");
        }
    }//GEN-LAST:event_txtBuscarFocusLost

    private Recordatorios obtenerRecordatorios(){
    Recordatorios elRecordatorios = new Recordatorios();
    elRecordatorios.setIdrecordatorios((Integer) txtIdRecordatorios.getValue());
    elRecordatorios.setTitulo(txtTitulo.getText());
    elRecordatorios.setMensaje(txtMensaje.getText());
    String fechaTexto = txtFecha.getText();
    if (fechaTexto != null && !fechaTexto.isEmpty() && !fechaTexto.equals("Escribe la fecha") && !fechaTexto.equals("Escriba fecha")) {
        elRecordatorios.setFecha_recordatorio(LocalDate.parse(fechaTexto, DateTimeFormatter.ofPattern("yyyy-MM-dd")));
    }
    return elRecordatorios;
}
    private void llenarTablaConBusqueda(String busqueda){
    Recordatorios unRecordatorios = new Recordatorios();
    DefaultTableModel tabla = (DefaultTableModel)tblRecordatorios.getModel();
    Iterator<Recordatorios> itRecordatorios = unRecordatorios.buscar(busqueda);
    Object[] filaRecordatorios = new Object[tblRecordatorios.getColumnCount()];
    tabla.setRowCount(0); 
    while (itRecordatorios.hasNext()) {
    unRecordatorios = itRecordatorios.next();
    filaRecordatorios[0] = unRecordatorios.getIdrecordatorios();
    filaRecordatorios[1] = unRecordatorios.getTitulo();
    filaRecordatorios[2] = unRecordatorios.getMensaje();
    filaRecordatorios[3] = unRecordatorios.getFecha_recordatorio();
    ((DefaultTableModel)tblRecordatorios.getModel()).addRow(filaRecordatorios);
}
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnInsertar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblRecordatorios;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JFormattedTextField txtIdRecordatorios;
    private javax.swing.JTextField txtMensaje;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
