/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package vista;
import java.beans.PropertyVetoException;
import modelo.ConexionBD;
/**
 *
 * @author LENOVO
 */
public class MDISalon extends javax.swing.JFrame {
    FRMUsuario fUsuario;
    FRMServicios fServicio;
    FRMProductos fProducto;
    FRMPerfiles fPerfiles;
    FRMCitas fCita;
    FRMCatalogo_Precios fCatalogo;
    FRMBloqueos fBloqueos;
    FRMAgenda FAgenda;
    
    /**
     * Creates new form MDIApplication
     */
    public MDISalon() {
        initComponents();
        fUsuario = new FRMUsuario();
        fServicio=new FRMServicios();
        fProducto=new FRMProductos();
        fPerfiles=new FRMPerfiles();
        fCita=new FRMCitas();
        fCatalogo=new FRMCatalogo_Precios();
        fBloqueos=new FRMBloqueos();
        FAgenda=new FRMAgenda();
        
        escritorio.add(fUsuario);
        escritorio.add(fServicio);
        escritorio.add(fProducto);
        escritorio.add(fPerfiles);
        escritorio.add(fCita);
        escritorio.add(fCatalogo);
        escritorio.add(fBloqueos);
        escritorio.add(FAgenda);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        MNUAdministrar = new javax.swing.JMenu();
        itemUsuario = new javax.swing.JMenuItem();
        itemServicios = new javax.swing.JMenuItem();
        itemProductos = new javax.swing.JMenuItem();
        itemPerfiles = new javax.swing.JMenuItem();
        itemCitas = new javax.swing.JMenuItem();
        itemCatalogo = new javax.swing.JMenuItem();
        itemBloqueos = new javax.swing.JMenuItem();
        itemAgenda = new javax.swing.JMenuItem();
        itemSalir = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        cutMenuItem = new javax.swing.JMenuItem();
        copyMenuItem = new javax.swing.JMenuItem();
        pasteMenuItem = new javax.swing.JMenuItem();
        deleteMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        escritorio.setBackground(new java.awt.Color(204, 204, 255));

        menuBar.setBackground(new java.awt.Color(153, 153, 255));

        MNUAdministrar.setBackground(new java.awt.Color(255, 204, 255));
        MNUAdministrar.setMnemonic('f');
        MNUAdministrar.setText("Administrar");

        itemUsuario.setMnemonic('o');
        itemUsuario.setText("Usuario");
        itemUsuario.addActionListener(this::itemUsuarioActionPerformed);
        MNUAdministrar.add(itemUsuario);

        itemServicios.setMnemonic('s');
        itemServicios.setText("Servicios");
        itemServicios.addActionListener(this::itemServiciosActionPerformed);
        MNUAdministrar.add(itemServicios);

        itemProductos.setText("Productos");
        itemProductos.addActionListener(this::itemProductosActionPerformed);
        MNUAdministrar.add(itemProductos);

        itemPerfiles.setText("Perfiles");
        itemPerfiles.addActionListener(this::itemPerfilesActionPerformed);
        MNUAdministrar.add(itemPerfiles);

        itemCitas.setText("Citas");
        itemCitas.addActionListener(this::itemCitasActionPerformed);
        MNUAdministrar.add(itemCitas);

        itemCatalogo.setText("Catalogo");
        itemCatalogo.addActionListener(this::itemCatalogoActionPerformed);
        MNUAdministrar.add(itemCatalogo);

        itemBloqueos.setText("Bloqueos");
        itemBloqueos.addActionListener(this::itemBloqueosActionPerformed);
        MNUAdministrar.add(itemBloqueos);

        itemAgenda.setText("Agenda");
        itemAgenda.addActionListener(this::itemAgendaActionPerformed);
        MNUAdministrar.add(itemAgenda);

        itemSalir.setMnemonic('x');
        itemSalir.setText("Salir");
        itemSalir.addActionListener(this::itemSalirActionPerformed);
        MNUAdministrar.add(itemSalir);

        menuBar.add(MNUAdministrar);

        editMenu.setMnemonic('e');
        editMenu.setText("Edit");

        cutMenuItem.setMnemonic('t');
        cutMenuItem.setText("Cut");
        editMenu.add(cutMenuItem);

        copyMenuItem.setMnemonic('y');
        copyMenuItem.setText("Copy");
        editMenu.add(copyMenuItem);

        pasteMenuItem.setMnemonic('p');
        pasteMenuItem.setText("Paste");
        editMenu.add(pasteMenuItem);

        deleteMenuItem.setMnemonic('d');
        deleteMenuItem.setText("Delete");
        editMenu.add(deleteMenuItem);

        menuBar.add(editMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Help");

        contentMenuItem.setMnemonic('c');
        contentMenuItem.setText("Contents");
        helpMenu.add(contentMenuItem);

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("About");
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSalirActionPerformed
                ConexionBD.desconectar();
        try{
            fUsuario.setClosed(true);
            
        }catch(PropertyVetoException ex){
            System.err.println("Error al salir:"+ex.getMessage());
        }
        System.exit(0);     
    }//GEN-LAST:event_itemSalirActionPerformed

    private void itemUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemUsuarioActionPerformed
        // TODO add your handling code here:
        fUsuario.setVisible(true);
    }//GEN-LAST:event_itemUsuarioActionPerformed

    private void itemBloqueosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemBloqueosActionPerformed
        fBloqueos.setVisible(true);
    }//GEN-LAST:event_itemBloqueosActionPerformed

    private void itemServiciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemServiciosActionPerformed
         fServicio.setVisible(true);
    }//GEN-LAST:event_itemServiciosActionPerformed

    private void itemProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemProductosActionPerformed
        fProducto.setVisible(true);
    }//GEN-LAST:event_itemProductosActionPerformed

    private void itemPerfilesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemPerfilesActionPerformed
        fPerfiles.setVisible(true);
    }//GEN-LAST:event_itemPerfilesActionPerformed

    private void itemCitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCitasActionPerformed
         fCita.setVisible(true);
    }//GEN-LAST:event_itemCitasActionPerformed

    private void itemCatalogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCatalogoActionPerformed
        fCatalogo.setVisible(true);
    }//GEN-LAST:event_itemCatalogoActionPerformed

    private void itemAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAgendaActionPerformed
         FAgenda.setVisible(true);
    }//GEN-LAST:event_itemAgendaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MDISalon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MDISalon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MDISalon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MDISalon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                modelo.ConexionBD.getInstance();
                new MDISalon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MNUAdministrar;
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem contentMenuItem;
    private javax.swing.JMenuItem copyMenuItem;
    private javax.swing.JMenuItem cutMenuItem;
    private javax.swing.JMenuItem deleteMenuItem;
    private javax.swing.JMenu editMenu;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuItem itemAgenda;
    private javax.swing.JMenuItem itemBloqueos;
    private javax.swing.JMenuItem itemCatalogo;
    private javax.swing.JMenuItem itemCitas;
    private javax.swing.JMenuItem itemPerfiles;
    private javax.swing.JMenuItem itemProductos;
    private javax.swing.JMenuItem itemSalir;
    private javax.swing.JMenuItem itemServicios;
    private javax.swing.JMenuItem itemUsuario;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem pasteMenuItem;
    // End of variables declaration//GEN-END:variables

}
