/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package vista;
import java.beans.PropertyVetoException;
import modelo.ConexionBD;
import modelo.Usuario;
/**
 *
 * @author LENOVO
 */
public class MDISalon extends javax.swing.JFrame {
    FRMUsuario fUsuario;
    FRMServicios fServicio;
    FRMProductos fProducto;
    FRMPerfiles fPerfiles;
    FRMCitas fCita;
    FRMCatalogo_Precios fCatalogo;
    FRMBloqueos fBloqueos;
    FRMAgenda FAgenda;
    Login flogin;

    /**
     * Creates new form MDIApplication
     */
    public MDISalon() {
        initComponents();
        inicializarFormularios();
        flogin = new Login(this);

        dpanellogin.add(flogin);
        int x = (dpanellogin.getWidth() - flogin.getWidth()) / 2;
        int y = (dpanellogin.getHeight() - flogin.getHeight()) / 2;
        flogin.setLocation(x, y);
        flogin.setVisible(true);
    }

    private void inicializarFormularios() {
        ConexionBD.getInstance();
        fUsuario = new FRMUsuario();
        fServicio = new FRMServicios();
        fProducto = new FRMProductos();
        fPerfiles = new FRMPerfiles();
        fCita = new FRMCitas();
        fCatalogo = new FRMCatalogo_Precios();
        fBloqueos = new FRMBloqueos();
        FAgenda = new FRMAgenda();
        escritorio.add(fUsuario);
        escritorio.add(fServicio);
        escritorio.add(fProducto);
        escritorio.add(fPerfiles);
        escritorio.add(fCita);
        escritorio.add(fCatalogo);
        escritorio.add(fBloqueos);
        escritorio.add(FAgenda);
    }


    public void abrirCrearCuenta() {
        FRMCrearcuenta crearCuenta = new FRMCrearcuenta();
        dpanellogin.add(crearCuenta);
        int x = (dpanellogin.getWidth() - crearCuenta.getWidth()) / 2;
        int y = (dpanellogin.getHeight() - crearCuenta.getHeight()) / 2;
        crearCuenta.setLocation(x, y);
        crearCuenta.setVisible(true);
    }

    public void mostrarLogin() {
        dpanellogin.removeAll();
        ConexionBD.reconectar();
        flogin = new Login(this);
        dpanellogin.add(flogin);
        int x = (dpanellogin.getWidth() - flogin.getWidth()) / 2;
        int y = (dpanellogin.getHeight() - flogin.getHeight()) / 2;
        flogin.setLocation(x, y);
        flogin.setVisible(true);
        dpanellogin.repaint();
    }

    public void mostrarDashboard(Usuario usuario) {
        dpanellogin.removeAll();
        if ("admin".equals(usuario.getRol())) {
            FRMdas_admin dasAdmin = new FRMdas_admin(this, usuario);
            dpanellogin.add(dasAdmin);
            dasAdmin.setVisible(true);
        } else {
            FRMdas_clien dasClien = new FRMdas_clien(this, usuario);
            dpanellogin.add(dasClien);
            dasClien.setVisible(true);
        }
        dpanellogin.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        dpanellogin = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        MNUAdministrar = new javax.swing.JMenu();
        itemUsuario = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();
        itemSalir = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        cutMenuItem = new javax.swing.JMenuItem();
        copyMenuItem = new javax.swing.JMenuItem();
        pasteMenuItem = new javax.swing.JMenuItem();
        deleteMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        escritorio.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout dpanelloginLayout = new javax.swing.GroupLayout(dpanellogin);
        dpanellogin.setLayout(dpanelloginLayout);
        dpanelloginLayout.setHorizontalGroup(
            dpanelloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 840, Short.MAX_VALUE)
        );
        dpanelloginLayout.setVerticalGroup(
            dpanelloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );

        escritorio.add(dpanellogin);
        dpanellogin.setBounds(90, 30, 840, 430);

        menuBar.setBackground(new java.awt.Color(255, 204, 255));
        menuBar.setForeground(new java.awt.Color(204, 153, 255));
        menuBar.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N

        MNUAdministrar.setBackground(new java.awt.Color(255, 204, 255));
        MNUAdministrar.setMnemonic('f');
        MNUAdministrar.setText("Administrar");

        itemUsuario.setMnemonic('o');
        itemUsuario.setText("Usuario");
        itemUsuario.addActionListener(this::itemUsuarioActionPerformed);
        MNUAdministrar.add(itemUsuario);

        jMenuItem1.setText("Perfiles");
        jMenuItem1.addActionListener(this::itemPerfilesActionPerformed);
        MNUAdministrar.add(jMenuItem1);

        jMenuItem2.setText("Bloqueos");
        jMenuItem2.addActionListener(this::itemBloqueosActionPerformed);
        MNUAdministrar.add(jMenuItem2);

        jMenuItem3.setText("Servicios");
        jMenuItem3.addActionListener(this::itemServiciosActionPerformed);
        MNUAdministrar.add(jMenuItem3);

        jMenuItem4.setText("Productos");
        jMenuItem4.addActionListener(this::itemProductosActionPerformed);
        MNUAdministrar.add(jMenuItem4);

        jMenuItem5.setText("Catalogo");
        jMenuItem5.addActionListener(this::itemCatalogoActionPerformed);
        MNUAdministrar.add(jMenuItem5);

        jMenuItem6.setText("Citas");
        jMenuItem6.addActionListener(this::itemCitasActionPerformed);
        MNUAdministrar.add(jMenuItem6);

        jMenuItem7.setText("Agenda");
        jMenuItem7.addActionListener(this::itemAgendaActionPerformed);
        MNUAdministrar.add(jMenuItem7);

        saveMenuItem.setMnemonic('s');
        saveMenuItem.setText("Save");
        MNUAdministrar.add(saveMenuItem);

        itemSalir.setMnemonic('x');
        itemSalir.setText("Salir");
        itemSalir.addActionListener(this::itemSalirActionPerformed);
        MNUAdministrar.add(itemSalir);

        menuBar.add(MNUAdministrar);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Help");

        contentMenuItem.setMnemonic('c');
        contentMenuItem.setText("Contents");
        helpMenu.add(contentMenuItem);

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("About");
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        editMenu.setMnemonic('e');
        editMenu.setText("Edit");

        cutMenuItem.setMnemonic('t');
        cutMenuItem.setText("Cut");
        editMenu.add(cutMenuItem);

        copyMenuItem.setMnemonic('y');
        copyMenuItem.setText("Copy");
        editMenu.add(copyMenuItem);

        pasteMenuItem.setMnemonic('p');
        pasteMenuItem.setText("Paste");
        editMenu.add(pasteMenuItem);

        deleteMenuItem.setMnemonic('d');
        deleteMenuItem.setText("Delete");
        editMenu.add(deleteMenuItem);

        menuBar.add(editMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 1033, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(escritorio, javax.swing.GroupLayout.PREFERRED_SIZE, 571, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSalirActionPerformed
        ConexionBD.desconectar();
        if (fUsuario != null) {
            try{
                fUsuario.setClosed(true);
            }catch(PropertyVetoException ex){
                System.err.println("Error al salir:"+ex.getMessage());
            }
        }
        System.exit(0);     
    }//GEN-LAST:event_itemSalirActionPerformed

    private void itemUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemUsuarioActionPerformed
        // TODO add your handling code here:
        fUsuario.setVisible(true);
    }//GEN-LAST:event_itemUsuarioActionPerformed

    private void itemBloqueosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemBloqueosActionPerformed
        fBloqueos.setVisible(true);
    }//GEN-LAST:event_itemBloqueosActionPerformed

    private void itemServiciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemServiciosActionPerformed
         fServicio.setVisible(true);
    }//GEN-LAST:event_itemServiciosActionPerformed

    private void itemProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemProductosActionPerformed
        fProducto.setVisible(true);
    }//GEN-LAST:event_itemProductosActionPerformed

    private void itemPerfilesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemPerfilesActionPerformed
        fPerfiles.setVisible(true);
    }//GEN-LAST:event_itemPerfilesActionPerformed

    private void itemCitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCitasActionPerformed
         fCita.setVisible(true);
    }//GEN-LAST:event_itemCitasActionPerformed

    private void itemCatalogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCatalogoActionPerformed
        fCatalogo.setVisible(true);
    }//GEN-LAST:event_itemCatalogoActionPerformed

    private void itemAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAgendaActionPerformed
         FAgenda.setVisible(true);
    }//GEN-LAST:event_itemAgendaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MDISalon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MDISalon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MDISalon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MDISalon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MDISalon mdi = new MDISalon();
                mdi.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MNUAdministrar;
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem contentMenuItem;
    private javax.swing.JMenuItem copyMenuItem;
    private javax.swing.JMenuItem cutMenuItem;
    private javax.swing.JMenuItem deleteMenuItem;
    private javax.swing.JDesktopPane dpanellogin;
    private javax.swing.JMenu editMenu;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuItem itemSalir;
    private javax.swing.JMenuItem itemUsuario;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem pasteMenuItem;
    private javax.swing.JMenuItem saveMenuItem;
    // End of variables declaration//GEN-END:variables

}
